ITEM.name = "HE Grenade"
ITEM.description = "grenadeDesc"
ITEM.model = "models/weapons/w_grenade.mdl"
ITEM.class = "weapon_frag"
ITEM.weaponCategory = "grenade"
ITEM.classes = {CLASS_SGS, CLASS_OWS, CLASS_EMP, CLASS_REBEL}
ITEM.width = 1
ITEM.height = 1
ITEM.price = 350
ITEM.factions = {FACTION_CONSCRIPT}