
Schema.voices.Add("Combine", "0", "0.", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("Combine", "1", "1.", "npc/metropolice/vo/one.wav")
Schema.voices.Add("Combine", "10", "10.", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("Combine", "10-0 수색 중", "10-0, 비저레이터가 수색 중이다!", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
Schema.voices.Add("Combine", "100", "100.", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("Combine", "10-103 예상", "10-103 예상, 후방 병력에 알려라.", "npc/metropolice/vo/possible10-103alerttagunits.wav")
Schema.voices.Add("Combine", "10-107", "10-107 포착됐다, 공중 공격 요청한다.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
Schema.voices.Add("Combine", "10-108", "10-108 상황 발생!", "npc/metropolice/vo/wehavea10-108.wav")
Schema.voices.Add("Combine", "10-14", "10-14 근무 중, 코드 4.", "npc/metropolice/vo/holdingon10-14duty.wav")
Schema.voices.Add("Combine", "10-15", "10-15 준비하라.", "npc/metropolice/vo/preparefor1015.wav")
Schema.voices.Add("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("Combine", "10-25", "아무 병력, 10-25 용의자 보고하라.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
Schema.voices.Add("Combine", "10-30", "10-20에 10-30이 있다, 코드 2 진행하겠다.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav")
Schema.voices.Add("Combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
Schema.voices.Add("Combine", "10-65", "병력은 10-65 상태.", "npc/metropolice/vo/unitis10-65.wav")
Schema.voices.Add("Combine", "10-78", "10-78 지원, 대원이 위험하다!", "npc/metropolice/vo/dispatchIneed10-78.wav")
Schema.voices.Add("Combine", "10-8", "10-8, 대기 중.", "npc/metropolice/vo/ten8standingby.wav")
Schema.voices.Add("Combine", "10-8 수행 중", "병력은 10-8, 수행 중.", "npc/metropolice/vo/unitisonduty10-8.wav")
Schema.voices.Add("Combine", "10-91", "10-91 사망자 수는...", "npc/metropolice/vo/ten91dcountis.wav")
Schema.voices.Add("Combine", "10-97 GOA", "10-97, 용의자는 GOA 상태.", "npc/metropolice/vo/ten97suspectisgoa.wav")
Schema.voices.Add("Combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
Schema.voices.Add("Combine", "10-99", "경찰이 쓰러졌다, 여기는 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav")
Schema.voices.Add("Combine", "11-44", "11-44 데려와라, 지금 소탕한다.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
Schema.voices.Add("Combine", "11-6", "용의자 11-6, 여기는 10-20.", "npc/metropolice/vo/suspect11-6my1020is.wav")
Schema.voices.Add("Combine", "11-99", "11-99, 긴급 지원 바란다!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
Schema.voices.Add("Combine", "2", "2.", "npc/metropolice/vo/two.wav")
Schema.voices.Add("Combine", "20", "20.", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("Combine", "200", "200.", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("Combine", "3", "3.", "npc/metropolice/vo/three.wav")
Schema.voices.Add("Combine", "30", "30.", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("Combine", "300", "300.", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("Combine", "34S", "모든 병력 주의하라, 34-S 발생.", "npc/metropolice/vo/allunitsbol34sat.wav")
Schema.voices.Add("Combine", "4", "4.", "npc/metropolice/vo/four.wav")
Schema.voices.Add("Combine", "40", "40.", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("Combine", "404", "404 구역.", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("Combine", "408", "이곳에 408 사태 발생했다.", "npc/metropolice/vo/Ivegot408hereatlocation.wav")
Schema.voices.Add("Combine", "415B", "415-B 중.", "npc/metropolice/vo/is415b.wav")
Schema.voices.Add("Combine", "5", "5.", "npc/metropolice/vo/five.wav")
Schema.voices.Add("Combine", "50", "50.", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("Combine", "505", "공중 추적 지원 바람, 표적 505!", "npc/metropolice/vo/airwatchsubjectis505.wav")
Schema.voices.Add("Combine", "6", "6.", "npc/metropolice/vo/six.wav")
Schema.voices.Add("Combine", "60", "60.", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("Combine", "603", "603, 불법 침입.", "npc/metropolice/vo/unlawfulentry603.wav")
Schema.voices.Add("Combine", "63", "63, 비인가 구역 침입.", "npc/metropolice/vo/criminaltrespass63.wav")
Schema.voices.Add("Combine", "7", "7.", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("Combine", "70", "70.", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("Combine", "8", "8.", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("Combine", "80", "80.", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("Combine", "9", "9.", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("Combine", "90", "90.", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("Combine", "수류탄2", "수류탄이다!", "npc/metropolice/vo/thatsagrenade.wav")
Schema.voices.Add("Combine", "용의자 포착", "용의자 포착됐다!", "npc/metropolice/vo/acquiringonvisual.wav")
Schema.voices.Add("Combine", "지급하라", "지급하라.", "npc/metropolice/vo/administer.wav")
Schema.voices.Add("Combine", "용의자 무기 소지", "해당 용의자의 무기 소지 확인, 10-0.", "npc/metropolice/vo/confirmadw.wav")
Schema.voices.Add("Combine", "ㅇㅋ", "알았다.", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("Combine", "진입하라", "모든 병력, 진입하라!", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("Combine", "절단", "절단.", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("Combine", "반시민", "반-시민.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("Combine", "소독제", "소독제.", "npc/combine_soldier/vo/antiseptic.wav")
Schema.voices.Add("Combine", "알파", "알파.", "npc/combine_soldier/vo/apex.wav")
Schema.voices.Add("Combine", "적용", "적용.", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("Combine", "구속 위치", "모든 병력, 구속 위치로 이동하라!", "npc/metropolice/vo/movetoarrestpositions.wav")
Schema.voices.Add("Combine", "검문소", "검문소.", "npc/metropolice/vo/atcheckpoint.wav")
Schema.voices.Add("Combine", "위치 도착", "보호 기동대 위치 도착. 보고한다.", "npc/metropolice/vo/ptatlocationreport.wav")
Schema.voices.Add("Combine", "엄호하라 나간다", "엄호하라, 나간다!", "npc/metropolice/vo/backmeupImout.wav")
Schema.voices.Add("Combine", "지원", "지원!", "npc/metropolice/vo/backup.wav")
Schema.voices.Add("Combine", "브라보", "브라보.", "npc/combine_soldier/vo/blade.wav")
Schema.voices.Add("Combine", "용의자 다침", "용의자, 상처 입고 피를 흘리고 있다!", "npc/metropolice/vo/suspectisbleeding.wav")
Schema.voices.Add("Combine", "소탕하라", "기기에 포착된 범죄 현장을 소탕하라.", "npc/metropolice/vo/catchthatbliponstabilization.wav")
Schema.voices.Add("Combine", "단결", "구역 유지 중, 단결.", "npc/metropolice/vo/blockisholdingcohesive.wav")
Schema.voices.Add("Combine", "블록", "블록!", "npc/metropolice/vo/block.wav")
Schema.voices.Add("Combine", "243", "243 수색 지원할 공중 추적 바람.", "npc/metropolice/vo/cpbolforthat243.wav")
Schema.voices.Add("Combine", "베타", "베타.", "npc/combine_soldier/vo/boomer.wav")
Schema.voices.Add("Combine", "엄페물 제거하라", "엄폐물 제거하라!", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("Combine", "캔1", "저 캔을 집어라.", "npc/metropolice/vo/pickupthecan1.wav")
Schema.voices.Add("Combine", "캔2", "저 캔을 집으라고 했다.", "npc/metropolice/vo/pickupthecan3.wav")
Schema.voices.Add("Combine", "캔3", "이제, 휴지통에 넣어라.", "npc/metropolice/vo/putitinthetrash1.wav")
Schema.voices.Add("Combine", "캔4", '"휴지통에 넣어"라고 말했다!', "npc/metropolice/vo/putitinthetrash2.wav")
Schema.voices.Add("Combine", "캔5", "네가 넘어트렸잖아, 주워라.", "npc/metropolice/vo/youknockeditover.wav")
Schema.voices.Add("Combine", "운하", "운하.", "npc/metropolice/vo/canal.wav")
Schema.voices.Add("Combine", "운하 구역", "운하 구역!", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("Combine", "제거하라", "제거하라.", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("Combine", "불일치 확인", "불일치 없는지 확인하라.", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("Combine", "검문소로 이동하라", "지명된 검문소로 이동하라.", "npc/metropolice/vo/proceedtocheckpoints.wav")
Schema.voices.Add("Combine", "T94-322", "일반 공공 서비스 T94-322에 자원한 시민을 보고한다. 지금 보내도록 하겠다.", "npc/metropolice/vo/citizensummoned.wav")
Schema.voices.Add("Combine", "시민", "시민.", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("Combine", "사상자로 분류하라", "대상 상태를 사상자로 분류하라. 이 구역은 곧 소탕된다.", "npc/metropolice/vo/classifyasdbthisblockready.wav")
Schema.voices.Add("Combine", "처리했다", "처리했다.", "npc/combine_soldier/vo/cleaned.wav")
Schema.voices.Add("Combine", "이상 없음 코드 100", "이상 없음, 코드 100.", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("Combine", "용의자에 접근하라", "모든 병력, 용의자에 접근하라!", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("Combine", "접근 중", "접근 중!", "npc/combine_soldier/vo/closing.wav")
Schema.voices.Add("Combine", "코드 100", "코드 100.", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("Combine", "코드 2", "모든 병력, 코드 2!", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("Combine", "코드 3", "경찰이 쓰러졌다, 모든 병력은 10-20으로!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
Schema.voices.Add("Combine", "코드 7", "코드 7.", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("Combine", "저주받은 구역", "저주받은 구역!", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("Combine", "243 포착", "243 용의자 포착했다, 10-20.", "npc/metropolice/vo/contactwith243suspect.wav")
Schema.voices.Add("Combine", "중요도 2 발견", "중요도 2 용의자 발견!", "npc/metropolice/vo/contactwithpriority2.wav")
Schema.voices.Add("Combine", "포착", "포착!", "npc/combine_soldier/vo/contact.wav")
Schema.voices.Add("Combine", "격리되었다", "격리되었다.", "npc/combine_soldier/vo/contained.wav")
Schema.voices.Add("Combine", "647E 없음", "이 구역은 아무 이상이 없다, 647-E 보이지 않는다.", "npc/metropolice/vo/control100percent.wav")
Schema.voices.Add("Combine", "구역 통제", "구역 통제!", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("Combine", "확인 바람", "확인 바람.", "npc/metropolice/vo/copy.wav")
Schema.voices.Add("Combine", "엄호하라", "엄호하라!", "npc/combine_soldier/vo/coverhurt.wav")
Schema.voices.Add("Combine", "CP 연루됨", "CP 연루돼 있다, 지원하라!", "npc/metropolice/vo/cpiscompromised.wav")
Schema.voices.Add("Combine", "구축 요청", "지역 구축 요청한다, 위치는...", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
Schema.voices.Add("Combine", "CP 침략됨", "CP가 침략되었다, 봉쇄가 무너졌다!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
Schema.voices.Add("Combine", "대거", "대거.", "npc/combine_soldier/vo/dagger.wav")
Schema.voices.Add("Combine", "-", "-", "npc/combine_soldier/vo/dash.wav")
Schema.voices.Add("Combine", "사망자 수", "사망자 수.", "npc/metropolice/vo/dbcountis.wav")
Schema.voices.Add("Combine", "디펜더", "디펜더!", "npc/metropolice/vo/defender.wav")
Schema.voices.Add("Combine", "관할 구역", "관할 구역.", "npc/metropolice/vo/deservicedarea.wav")
Schema.voices.Add("Combine", "용의자 지명", "용의자 지명.", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("Combine", "엄폐물 파괴하라", "엄폐물 파괴하라!", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("Combine", "분산시켜라", "사이를 쏴서 힘을 분산시켜라!", "npc/metropolice/vo/firetodislocateinterpose.wav")
Schema.voices.Add("Combine", "바리케이드 철수 중", "바리케이트 철수 중.", "npc/metropolice/vo/dismountinghardpoint.wav")
Schema.voices.Add("Combine", "사진", "사진을 갱신 중이다.", "npc/metropolice/vo/dispupdatingapb.wav")
Schema.voices.Add("Combine", "유통 구역", "유통 구역.", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("Combine", "기록", "기록.", "npc/metropolice/vo/document.wav")
Schema.voices.Add("Combine", "동작 그만", "동작 그만!", "npc/metropolice/vo/dontmove.wav")
Schema.voices.Add("Combine", "에코", "에코.", "npc/combine_soldier/vo/echo.wav")
Schema.voices.Add("Combine", "수행 중", "수행 중!", "npc/combine_soldier/vo/engaging.wav")
Schema.voices.Add("Combine", "후퇴", "후퇴하라, 새 CP를 구축하라!", "npc/metropolice/vo/establishnewcp.wav")
Schema.voices.Add("Combine", "목표를 쏴라", "목표를 향해 쏴라!", "npc/metropolice/vo/firingtoexposetarget.wav")
Schema.voices.Add("Combine", "외부 관할권", "외부 관할권.", "npc/metropolice/vo/externaljurisdiction.wav")
Schema.voices.Add("Combine", "최종 평결", "최종 평결, 집행 완료.", "npc/metropolice/vo/finalverdictadministered.wav")
Schema.voices.Add("Combine", "경고3", "최종 경고!", "npc/metropolice/vo/finalwarning.wav")
Schema.voices.Add("Combine", "경고ㅂㅋ", "첫번째 경고다, 비켜라!", "npc/metropolice/vo/firstwarningmove.wav")
Schema.voices.Add("Combine", "피스트", "피스트.", "npc/combine_soldier/vo/fist.wav")
Schema.voices.Add("Combine", "플래시", "플래시.", "npc/combine_soldier/vo/flash.wav")
Schema.voices.Add("Combine", "폭스트롯", "폭스트롯.", "npc/combine_soldier/vo/flatline.wav")
Schema.voices.Add("Combine", "플러시", "플러시.", "npc/combine_soldier/vo/flush.wav")
Schema.voices.Add("Combine", "네크로틱2", "네크로틱이 날뛰고 있다!", "npc/metropolice/vo/freenecrotics.wav")
Schema.voices.Add("Combine", "숙여", "숙여!", "npc/metropolice/vo/getdown.wav")
Schema.voices.Add("Combine", "나가", "이제 여기서 나가라.", "npc/metropolice/vo/getoutofhere.wav")
Schema.voices.Add("Combine", "647E 포착 중", "로컬 감시조에서 647-E를 포착 중.", "npc/metropolice/vo/stillgetting647e.wav")
Schema.voices.Add("Combine", "고스트", "고스트.", "npc/combine_soldier/vo/ghost.wav")
Schema.voices.Add("Combine", "다시 가라", "PT, 다시 가라.", "npc/metropolice/vo/ptgoagain.wav")
Schema.voices.Add("Combine", "ㄱㄱ", "이동하라!", "npc/combine_soldier/vo/gosharp.wav")
Schema.voices.Add("Combine", "엄호하라 들어간다", "엄호하라, 들어간다!", "npc/metropolice/vo/covermegoingin.wav")
Schema.voices.Add("Combine", "시체 발견", "시체 발견, 11-42 취소하라.", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
Schema.voices.Add("Combine", "다시 포착했다", "다시 포착했다. 용의자 위치, 10-20.", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
Schema.voices.Add("Combine", "공범자 잡았다", "여기 공범자 한 명 잡았다!", "npc/metropolice/vo/gotoneaccomplicehere.wav")
Schema.voices.Add("Combine", "용의자1 잡았다", "여기 용의자 1 잡았다!", "npc/metropolice/vo/gotsuspect1here.wav")
Schema.voices.Add("Combine", "수류탄", "수류탄!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("Combine", "그리드", "그리드.", "npc/combine_soldier/vo/grid.wav")
Schema.voices.Add("Combine", "ㅋㅋ", "*(조용한 웃음소리)*", "npc/metropolice/vo/chuckle.wav")
Schema.voices.Add("Combine", "해머", "해머.", "npc/combine_soldier/vo/hammer.wav")
Schema.voices.Add("Combine", "현장에 도착했다", "현장에 도착했다, 준비 완료!", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
Schema.voices.Add("Combine", "현장 수색 중", "현장 수색 중.", "npc/metropolice/vo/hardpointscanning.wav")
Schema.voices.Add("Combine", "호텔", "호텔.", "npc/combine_soldier/vo/helix.wav")
Schema.voices.Add("Combine", "도와줘", "도와줘!", "npc/metropolice/vo/help.wav")
Schema.voices.Add("Combine", "히어로", "히어로!", "npc/metropolice/vo/hero.wav")
Schema.voices.Add("Combine", "148", "148 코드 발생!", "npc/metropolice/vo/hesgone148.wav")
Schema.voices.Add("Combine", "중요 지역", "중요 지역.", "npc/metropolice/vo/highpriorityregion.wav")
Schema.voices.Add("Combine", "ㄱㄷ", "거기서 멈춰라!", "npc/metropolice/vo/holditrightthere.wav")
Schema.voices.Add("Combine", "위치 사수", "보호 기동대, 이 위치를 사수하라.", "npc/metropolice/vo/holdthisposition.wav")
Schema.voices.Add("Combine", "멈춰라", "멈춰라!", "npc/metropolice/vo/holdit.wav")
Schema.voices.Add("Combine", "헌터", "헌터.", "npc/combine_soldier/vo/hunter.wav")
Schema.voices.Add("Combine", "허리케인", "허리케인.", "npc/combine_soldier/vo/hurricane.wav")
Schema.voices.Add("Combine", "움직여2", "움직이라고 말했다.", "npc/metropolice/vo/Isaidmovealong.wav")
Schema.voices.Add("Combine", "인디아", "인디아.", "npc/combine_soldier/vo/ice.wav")
Schema.voices.Add("Combine", "ㄹㄷ", "준비됐다.", "npc/metropolice/vo/inposition.wav")
Schema.voices.Add("Combine", "접근", "접근.", "npc/combine_soldier/vo/inbound.wav")
Schema.voices.Add("Combine", "감염 확인", "감염 확인.", "npc/combine_soldier/vo/infected.wav")
Schema.voices.Add("Combine", "감염", "감염!", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("Combine", "감염된 구역", "감염된 구역.", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("Combine", "주입", "주입!", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("Combine", "투입", "투입.", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("Combine", "차단", "차단!", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("Combine", "결합", "결합!", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("Combine", "조사", "조사.", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("Combine", "조사 중", "10-103 조사 중.", "npc/metropolice/vo/investigating10-103.wav")
Schema.voices.Add("Combine", "이온", "이온.", "npc/combine_soldier/vo/ion.wav")
Schema.voices.Add("Combine", "10-108 발생", "10-108 발생!", "npc/metropolice/vo/is10-108.wav")
Schema.voices.Add("Combine", "10-8 대기 중", "병력은 10-8, 대기 중.", "npc/metropolice/vo/unitis10-8standingby.wav")
Schema.voices.Add("Combine", "접근 중3", "용의자에 접근 중!", "npc/metropolice/vo/isclosingonsuspect.wav")
Schema.voices.Add("Combine", "쓰러졌다", "쓰러졌다!", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("Combine", "도착 중", "병력 도착 중.", "npc/combine_soldier/vo/unitisinbound.wav")
Schema.voices.Add("Combine", "이동 중", "병력 이동 중.", "npc/combine_soldier/vo/unitismovingin.wav")
Schema.voices.Add("Combine", "접근 중2", "접근 중이다!", "npc/metropolice/vo/ismovingin.wav")
Schema.voices.Add("Combine", "무반응", "반응이 없다.", "npc/metropolice/vo/ispassive.wav")
Schema.voices.Add("Combine", "ㄹㄷ2", "준비가 됬다!", "npc/metropolice/vo/isreadytogo.wav")
Schema.voices.Add("Combine", "격리", "격리!", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("Combine", "줄리엣", "줄리엣.", "npc/combine_soldier/vo/jet.wav")
Schema.voices.Add("Combine", "저지", "저지.", "npc/combine_soldier/vo/judge.wav")
Schema.voices.Add("Combine", "판결", "용의자, 판결을 받을 준비를 하라!", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("Combine", "진압 관할권", "진압 관할권.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
Schema.voices.Add("Combine", "주리", "주리!", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("Combine", "계속 움직여라", "계속 움직여라!", "npc/metropolice/vo/keepmoving.wav")
Schema.voices.Add("Combine", "킬로", "킬로.", "npc/combine_soldier/vo/kilo.wav")
Schema.voices.Add("Combine", "킹", "킹!", "npc/metropolice/vo/king.wav")
Schema.voices.Add("Combine", "마지막 포착 위치", "의심 중, 마지막 포착 위치.", "npc/metropolice/vo/hidinglastseenatrange.wav")
Schema.voices.Add("Combine", "리더", "리더.", "npc/combine_soldier/vo/leader.wav")
Schema.voices.Add("Combine", "레벨 3", "여기에 레벨 3 시민 사생활 침해자가 있다!", "npc/metropolice/vo/level3civilprivacyviolator.wav")
Schema.voices.Add("Combine", "라인", "라인!", "npc/metropolice/vo/line.wav")
Schema.voices.Add("Combine", "위치", "위치?", "npc/metropolice/vo/location.wav")
Schema.voices.Add("Combine", "위치 사수", "모든 병력, 위치를 사수하라!", "npc/metropolice/vo/lockyourposition.wav")
Schema.voices.Add("Combine", "사수", "사수!", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("Combine", "조심해", "조심해!", "npc/metropolice/vo/lookout.wav")
Schema.voices.Add("Combine", "기생충 조심", "기생충 조심하라!", "npc/metropolice/vo/looseparasitics.wav")
Schema.voices.Add("Combine", "추적 실패", "추적 실패!", "npc/combine_soldier/vo/lostcontact.wav")
Schema.voices.Add("Combine", "실탄 부족", "실탄이 부족하다, 엄폐하겠다!", "npc/metropolice/vo/runninglowonverdicts.wav")
Schema.voices.Add("Combine", "마이크", "마이크.", "npc/combine_soldier/vo/mace.wav")
Schema.voices.Add("Combine", "CP 사수", "모든 병력, 이 CP 사수하라!", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("Combine", "불순종", "불순종 소환장 발행 중.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
Schema.voices.Add("Combine", "10-107 불순종", "10-20에서 10-107의 불순종, 구속 진행.", "npc/metropolice/vo/malcompliant10107my1020.wav")
Schema.voices.Add("Combine", "악성", "악성!", "npc/metropolice/vo/malignant.wav")
Schema.voices.Add("Combine", "사진 일치", "APB 사진과 일치한다.", "npc/metropolice/vo/matchonapblikeness.wav")
Schema.voices.Add("Combine", "경미한 부상", "경미한 부상이다, 임무 재개 중!", "npc/metropolice/vo/minorhitscontinuing.wav")
Schema.voices.Add("Combine", "움직여", "움직여!", "npc/metropolice/vo/move.wav")
Schema.voices.Add("Combine", "즉시 물러나라", "즉시 물러나라!", "npc/metropolice/vo/movebackrightnow.wav")
Schema.voices.Add("Combine", "진입하라", "진입하라!", "npc/combine_soldier/vo/movein.wav")
Schema.voices.Add("Combine", "엄호 위치로 이동", "엄호 위치로 이동한다!", "npc/metropolice/vo/movingtocover.wav")
Schema.voices.Add("Combine", "현장으로 이동", "현장으로 이동한다!", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("Combine", "네크로틱", "네크로틱!", "npc/metropolice/vo/necrotics.wav")
Schema.voices.Add("Combine", "지원이 필요한가", "지원이 필요한가?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("Combine", "부상", "부상 당한 경찰이 있다, 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
Schema.voices.Add("Combine", "지원 요청", "경찰이 지원 요청한다!", "npc/metropolice/vo/officerneedshelp.wav")
Schema.voices.Add("Combine", "10-107 없음", "이상 없음, 10-107 없음.", "npc/metropolice/vo/clearno647no10-107.wav")
Schema.voices.Add("Combine", "시야 미확보", "시야 미확보!", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("Combine", "괜찮아", "아니, 괜찮아.", "vo/trainyard/ba_noimgood.wav")
Schema.voices.Add("Combine", "용의자 안보임", "현재 용의자가 보이지 않는다.", "npc/metropolice/vo/novisualonupi.wav")
Schema.voices.Add("Combine", "노매드", "노매드.", "npc/combine_soldier/vo/nomad.wav")
Schema.voices.Add("Combine", "비감시", "비감시 영역.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("Combine", "태그 없는 바이롬", "태그 없는 바이롬을 발견했다!", "npc/metropolice/vo/non-taggedviromeshere.wav")
Schema.voices.Add("Combine", "노벰버", "노벰버.", "npc/combine_soldier/vo/nova.wav")
Schema.voices.Add("Combine", "좋아", "좋아.", "vo/trainyard/ba_thatbeer01.wav")
Schema.voices.Add("Combine", "확산", "확산!", "npc/combine_soldier/vo/outbreak.wav")
Schema.voices.Add("Combine", "보고한다", "보고한다.", "npc/combine_soldier/vo/overwatch.wav")
Schema.voices.Add("Combine", "진압 중", "진압 중!", "npc/metropolice/vo/pacifying.wav")
Schema.voices.Add("Combine", "고통", "*고통에 찬 소리*", "npc/metropolice/pain1.wav")
Schema.voices.Add("Combine", "고통2", "*고통에 찬 소리*", "npc/metropolice/pain2.wav")
Schema.voices.Add("Combine", "고통3", "*고통에 찬 소리*", "npc/metropolice/pain3.wav")
Schema.voices.Add("Combine", "고통4", "*고통에 찬 소리*", "npc/metropolice/pain4.wav")
Schema.voices.Add("Combine", "정찰", "정찰!", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("Combine", "파파", "파파.", "npc/combine_soldier/vo/payback.wav")
Schema.voices.Add("Combine", "팬텀", "팬텀.", "npc/combine_soldier/vo/phantom.wav")
Schema.voices.Add("Combine", "647E", "647-E 상태를 확인한 사람 또 있나?", "npc/metropolice/vo/anyonepickup647e.wav")
Schema.voices.Add("Combine", "접전지 위치", "접전지 위치, 준비 완료.", "npc/metropolice/vo/inpositionathardpoint.wav")
Schema.voices.Add("Combine", "진압 대기 중", "진압 대기 중.", "npc/metropolice/vo/positiontocontain.wav")
Schema.voices.Add("Combine", "404 예상", "여기에 404 발생 예상!", "npc/metropolice/vo/possible404here.wav")
Schema.voices.Add("Combine", "647E 예상", "647-E 상황 예상, 공중 추적 요청한다.", "npc/metropolice/vo/possible647erequestairwatch.wav")
Schema.voices.Add("Combine", "공범자", "공범자로 의심되는 자를 보고한다.", "npc/metropolice/vo/reportsightingsaccomplices.wav")
Schema.voices.Add("Combine", "레벨 3 예상", "레벨 3 시민 사생활 침해자가 있다!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
Schema.voices.Add("Combine", "판결 준비 중", "10-107, 판결을 준비 중이다.", "npc/metropolice/vo/preparingtojudge10-107.wav")
Schema.voices.Add("Combine", "보호", "보호!", "npc/metropolice/vo/preserve.wav")
Schema.voices.Add("Combine", "압력", "압력!", "npc/metropolice/vo/pressure.wav")
Schema.voices.Add("Combine", "중요도 1", "중요도 1 용의자 발견했다.", "npc/metropolice/vo/confirmpriority1sighted.wav")
Schema.voices.Add("Combine", "중요도 2", "여기에 중요도 2 반시민이 있다!", "npc/metropolice/vo/priority2anticitizenhere.wav")
Schema.voices.Add("Combine", "생산 구역", "생산 구역.", "npc/metropolice/vo/productionblock.wav")
Schema.voices.Add("Combine", "기소 준비", "불순종 시민, 기소 준비를 마쳤다!", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
Schema.voices.Add("Combine", "수행", "수행!", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("Combine", "수행 중", "수행 중.", "npc/combine_soldier/vo/prosecuting.")
Schema.voices.Add("Combine", "보호 완료", "보호 완료.", "npc/metropolice/vo/protectioncomplete.wav")
Schema.voices.Add("Combine", "퀵", "퀵!", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("Combine", "퀘벡", "퀘벡.", "npc/combine_soldier/vo/quicksand.wav")
Schema.voices.Add("Combine", "범위", "범위:", "npc/combine_soldier/vo/range.wav")
Schema.voices.Add("Combine", "레인저", "레인저.", "npc/combine_soldier/vo/ranger.wav")
Schema.voices.Add("Combine", "레이저", "레이저.", "npc/combine_soldier/vo/razor.wav")
Schema.voices.Add("Combine", "절단 준비", "절단 준비 완료!", "npc/metropolice/vo/readytoamputate.wav")
Schema.voices.Add("Combine", "포격 준비", "포격 준비!", "npc/combine_soldier/vo/readycharges.wav")
Schema.voices.Add("Combine", "판결 준비", "판결 준비 완료.", "npc/metropolice/vo/readytojudge.wav")
Schema.voices.Add("Combine", "속행 준비", "속행 준비 완료!", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("Combine", "무기 준비", "무기 준비!", "npc/combine_soldier/vo/readyweapons.wav")
Schema.voices.Add("Combine", "리퍼", "리퍼.", "npc/combine_soldier/vo/reaper.wav")
Schema.voices.Add("Combine", "지원 팀", "지원 팀, 코드 3!", "npc/metropolice/vo/reinforcementteamscode3.wav")
Schema.voices.Add("Combine", "이상 없음", "이상 없음.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("Combine", "보고하라", "모든 병력, 위치 요청한다. 보고하라.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
Schema.voices.Add("Combine", "용의자 위치 보고", "모든 병력, 용의자 위치 보고하라!", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("Combine", "상황 보고하라", "CP 팀, 상황 보고하라.", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("Combine", "용도 변경", "용도 변경 지역.", "npc/metropolice/vo/repurposedarea.wav")
Schema.voices.Add("Combine", "거주 구역", "거주 구역.", "npc/metropolice/vo/residentialblock.wav")
Schema.voices.Add("Combine", "코드 3 응답", "현장의 모든 병력, 코드 3 응답하라!", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("Combine", "ㅇㅇ", "응답.", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("Combine", "제한", "제한!", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("Combine", "제한 구역", "제한 구역.", "npc/metropolice/vo/restrictedblock.wav")
Schema.voices.Add("Combine", "최종 제한 구역", "최종 제한 구역!", "npc/metropolice/vo/terminalrestrictionzone.wav")
Schema.voices.Add("Combine", "로미오", "로미오!", "npc/combine_soldier/vo/ripcord.wav")
Schema.voices.Add("Combine", "ㅇㅋ오버", "알았다, 오버!", "npc/metropolice/vo/rodgerthat.wav")
Schema.voices.Add("Combine", "롤러", "롤러!", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("Combine", "도망간다", "도망가고 있다!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("Combine", "코드 무시", "모든 병력, 코드 1 무시하고 이 CP를 사수하라!", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
Schema.voices.Add("Combine", "새비지", "새비지.", "npc/combine_soldier/vo/savage.wav")
Schema.voices.Add("Combine", "스카", "스카.", "npc/combine_soldier/vo/scar.wav")
Schema.voices.Add("Combine", "수색", "수색!", "npc/metropolice/vo/search.wav")
Schema.voices.Add("Combine", "용의자 찾는 중", "용의자 찾는 중, 상태 없음.", "npc/metropolice/vo/searchingforsuspect.wav")
Schema.voices.Add("Combine", "경고2", "이것은 두번째 경고다!", "npc/metropolice/vo/thisisyoursecondwarning.wav")
Schema.voices.Add("Combine", "미살균 확인", "미살균 구역인지 확인하라.", "npc/combine_soldier/vo/confirmsectornotsterile.wav")
Schema.voices.Add("Combine", "구역 미확보", "구역 미확보.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("Combine", "전진하라", "습격 지점 확보, 전진하라!", "npc/metropolice/vo/assaultpointsecureadvance.wav")
Schema.voices.Add("Combine", "처리 완수", "처리 완수.", "npc/combine_soldier/vo/secure.wav")
Schema.voices.Add("Combine", "선고되었다", "선고되었다.", "npc/metropolice/vo/sentencedelivered.wav")
Schema.voices.Add("Combine", "복무", "복무.", "npc/metropolice/vo/serve.wav")
Schema.voices.Add("Combine", "섀도", "섀도.", "npc/combine_soldier/vo/shadow.wav")
Schema.voices.Add("Combine", "이동 구역", "이동 구역.", "npc/combine_soldier/vo/sharpzone.wav")
Schema.voices.Add("Combine", "젠장", "젠장!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("Combine", "발사", "무기 발사, 적대적인 생명체 발견!", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
Schema.voices.Add("Combine", "SLAM", "SLAM.", "npc/combine_soldier/vo/slam.wav")
Schema.voices.Add("Combine", "슬래시", "슬래시.", "npc/combine_soldier/vo/slash.wav")
Schema.voices.Add("Combine", "반사회", "반사회.", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("Combine", "안정 지역", "이 지역은 안정되어 있다.", "npc/metropolice/vo/wearesociostablethislocation.wav")
Schema.voices.Add("Combine", "스피어", "스피어.", "npc/combine_soldier/vo/spear.wav")
Schema.voices.Add("Combine", "스탭", "스탭.", "npc/combine_soldier/vo/stab.wav")
Schema.voices.Add("Combine", "대기 중", "대기 중.", "npc/combine_soldier/vo/standingby].wav")
Schema.voices.Add("Combine", "스타", "스타.", "npc/combine_soldier/vo/star.wav")
Schema.voices.Add("Combine", "스테이션 구역", "스테이션 구역.", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("Combine", "경비하라", "경비하라.", "npc/combine_soldier/vo/stayalert.wav")
Schema.voices.Add("Combine", "살균", "살균!", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("Combine", "스팅어", "스팅어.", "npc/combine_soldier/vo/stinger.wav")
Schema.voices.Add("Combine", "스톰", "스톰.", "npc/combine_soldier/vo/storm.wav")
Schema.voices.Add("Combine", "스트라이커", "스트라이커.", "npc/combine_soldier/vo/striker.wav")
Schema.voices.Add("Combine", "대상은 505", "대상은 505!", "npc/metropolice/vo/subjectis505.wav")
Schema.voices.Add("Combine", "대상 빨라짐", "주목하라, 대상의 이동 속도가 빨라졌다!", "npc/metropolice/vo/subjectisnowhighspeed.wav")
Schema.voices.Add("Combine", "대상", "대상!", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("Combine", "시에라", "시에라.", "npc/combine_soldier/vo/sundown.wav")
Schema.voices.Add("Combine", "용의자 진입함", "용의자가 이 지역에 진입했다.", "npc/metropolice/vo/dispreportssuspectincursion.wav")
Schema.voices.Add("Combine", "용의자 이동함", "현재 용의자가 이동했다.", "npc/metropolice/vo/supsecthasmovednowto.wav")
Schema.voices.Add("Combine", "용의자 운하 사용 중", "용의자가 제한된 운하를 사용하고 있다.", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
Schema.voices.Add("Combine", "중재", "중재!", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("Combine", "스위퍼", "스위퍼.", "npc/combine_soldier/vo/sweeper.wav")
Schema.voices.Add("Combine", "정찰 중", "정찰 중!", "npc/combine_soldier/vo/sweepingin.wav")
Schema.voices.Add("Combine", "용의자 추적 중", "용의자 추적 중!", "npc/metropolice/vo/sweepingforsuspect.wav")
Schema.voices.Add("Combine", "스위프트", "스위프트.", "npc/combine_soldier/vo/swift.wav")
Schema.voices.Add("Combine", "소드", "소드.", "npc/combine_soldier/vo/sword.wav")
Schema.voices.Add("Combine", "10-91D 출현", "10-91D 출현!", "npc/metropolice/vo/tag10-91d.wav")
Schema.voices.Add("Combine", "벌레 출현", "벌레 출현!", "npc/metropolice/vo/tagonebug.wav")
Schema.voices.Add("Combine", "네크로틱 출현", "네크로틱 출현!", "npc/metropolice/vo/tagonenecrotic.wav")
Schema.voices.Add("Combine", "기생충 출현", "기생충 출현!", "npc/metropolice/vo/tagoneparasitic.wav")
Schema.voices.Add("Combine", "살펴보겠다", "살펴보고 오겠다!", "npc/metropolice/vo/goingtotakealook.wav")
Schema.voices.Add("Combine", "엄폐", "엄폐하라!", "npc/metropolice/vo/takecover.wav")
Schema.voices.Add("Combine", "탭", "탭!", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("Combine", "목표", "목표.", "npc/combine_soldier/vo/target.wav")
Schema.voices.Add("Combine", "전진", "팀 위치 도착, 전진!", "npc/metropolice/vo/teaminpositionadvance.wav")
Schema.voices.Add("Combine", "진압 대기 중2", "진압 팀, 현 위치에서 대기 중이다.", "npc/combine_soldier/vo/stabilizationteamholding.wav")
Schema.voices.Add("Combine", "저기 있다2", "저기 있다! 위치.", "npc/metropolice/vo/therehegoeshesat.wav")
Schema.voices.Add("Combine", "저기 있다", "저기 있다!", "npc/metropolice/vo/thereheis.wav")
Schema.voices.Add("Combine", "트래커", "트래커.", "npc/combine_soldier/vo/tracker.wav")
Schema.voices.Add("Combine", "통로 구역", "통로 구역.", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("Combine", "문제", "문제를 일으키러 가나?", "npc/metropolice/vo/lookingfortrouble.wav")
Schema.voices.Add("Combine", "UNDER FIRE", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav")
Schema.voices.Add("Combine", "유니폼", "유니폼.", "npc/combine_soldier/vo/uniform.wav")
Schema.voices.Add("Combine", "연합", "연합!", "npc/metropolice/vo/union.wav")
Schema.voices.Add("Combine", "용의자 위치 파악 안됨", "용의자 위치 파악 안됨.", "npc/metropolice/vo/suspectlocationunknown.wav")
Schema.voices.Add("Combine", "위쪽", "위쪽에 있다!", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("Combine", "용의자", "용의자.", "npc/metropolice/vo/upi.wav")
Schema.voices.Add("Combine", "용의자 미발견", "용의자 미발견.", "npc/metropolice/vo/utlsuspect.wav")
Schema.voices.Add("Combine", "내보내", "시민을 내보내라!", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("Combine", "뱀프", "뱀프.", "npc/combine_soldier/vo/vamp.wav")
Schema.voices.Add("Combine", "평결", "불순종 죄로 평결을 원하나?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
Schema.voices.Add("Combine", "바이스", "바이스!", "npc/metropolice/vo/vice.wav")
Schema.voices.Add("Combine", "빅터", "빅터!", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("Combine", "포착 확인", "포착 확인.", "npc/combine_soldier/vo/contactconfim.wav")
Schema.voices.Add("Combine", "엑소젠", "엑소젠 발견했다.", "npc/combine_soldier/vo/visualonexogens.wav")
Schema.voices.Add("Combine", "경고2 발부", "2차 경고 발부!", "npc/metropolice/vo/secondwarning.wav")
Schema.voices.Add("Combine", "폐수", "폐수.", "npc/metropolice/vo/wasteriver.wav")
Schema.voices.Add("Combine", "조심해라", "조심해라!", "npc/metropolice/vo/watchit.wav")
Schema.voices.Add("Combine", "와인더", "와인더.", "npc/combine_soldier/vo/winder.wav")
Schema.voices.Add("Combine", "인력", "인력 증원.", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("Combine", "마무리", "됐어, 마무리 해.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("Combine", "엑스레이", "엑스레이!", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("Combine", "옐로", "옐로!", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("Combine", "가도 좋다", "좋아. 가도 좋다.", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("Combine", "구역", "구역!", "npc/metropolice/vo/zone.wav")
Schema.voices.Add("Combine", "잡았다", "그를 잡았다.", "npc/combine_soldier/vo/affirmativewegothimnow.wav")
Schema.voices.Add("Combine", "경고1", "경고 1.", "npc/combine_soldier/vo/alert1.wav")
Schema.voices.Add("Combine", "반시민1", "반-시민 1.", "npc/combine_soldier/vo/anticitizenone.wav")
Schema.voices.Add("Combine", "방향", "방향:", "npc/combine_soldier/vo/bearing.wav")
Schema.voices.Add("Combine", "도", "도.", "npc/combine_soldier/vo/degrees.wav")
Schema.voices.Add("Combine", "ㅌㅌ", "흩어져라!", "npc/combine_soldier/vo/displace.wav")
Schema.voices.Add("Combine", "분산하라", "분산하라!", "npc/combine_soldier/vo/displace2.wav")
Schema.voices.Add("Combine", "수류탄 준비", "수류탄 준비.", "npc/combine_soldier/vo/extractoraway.wav")
Schema.voices.Add("Combine", "수류탄 투척", "수류탄 투척!", "npc/combine_soldier/vo/extractorisalive.wav")
Schema.voices.Add("Combine", "미터", "미터.", "npc/combine_soldier/vo/meters.wav")

Schema.voices.Add("Dispatch", "반동 세력 활동 레벨1", "주목, 당신은 시민의 의무 레벨: 2, 시민의 의무 레벨: 2에 응하지 않아 고발되었다. 반동 세력 활동 레벨: 1로 고발되었다. 보호 기동대, 수행 코드: 근무, 무력, 작전.", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "반시민", "지상 병력, 주목: 이 지역에 반동 세력이 있다는 보고를 받았다. 코드: 감금, 제거, 진압.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav", true)
Schema.voices.Add("Dispatch", "반사회", "보호 기동대, 경보: 이 지역에서 반동 세력 활동이 보이고 있다. 코드: 결집, 단속, 봉쇄.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "불응", "주목, 당신은 정부에 불응하여 고발되었다. 반동 세력 신분으로 확인되었다.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav", true)
Schema.voices.Add("Dispatch", "위치 확인", "주목, 해당 구역에 거주하는 모든 시민들은 해당 검사 위치를 확인하라.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav", true)
Schema.voices.Add("Dispatch", "자발적 판결권", "주목, 지상 보호 기동대, 현재 자발적 판결권이 발효되었다. 현재 자발적으로 판결을 선고할 수 있다. 코드: 절단, 이민, 확인.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "시민 이전", "시민에게 알린다, 협력에 불응하면 외계로 영구히 이전되는 처벌을 받게 될 것이다.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav", true)
Schema.voices.Add("Dispatch", "불법 공모", "시민에게 알린다, 방관하는 태도는 불법 공모 행위이다. 반행동을 목격할 경우 즉시 시민 보호 기동대에 신고하라.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav", true)
Schema.voices.Add("Dispatch", "시민권 박탈", "주목, 여러 반시민적 위반 행위로 인해 판결을 받았다. 시민권이 박탈되었다. 신분: 악적 존재.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav", true)
Schema.voices.Add("Dispatch", "보급 중단", "현 거주자 주목, 해당 구역은 반시민 활동 용인으로 고발되었다. 다섯 건의 식량 보급이 중단되었다.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "기피 행동", "주목, 기피 행동은 불응 범죄와 동일하게 취급된다. 지상 보호 기동대, 경보, 코드: 격리, 차출, 집행.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav", true)
Schema.voices.Add("Dispatch", "사회 반란 레벨1", "주목, 당신은 사회 반란 레벨: 1, 사회 반란 레벨: 1로 고발되었다. 보호 기동대 병력, 수행 코드: 근무, 무력, 자정.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "ID", "시민에게 알린다, 비상 ID 점검을 집행 중이다. 비상 ID 점검을 진행 중이다. 지정된 위치에서 결집하라.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav", true)
Schema.voices.Add("Dispatch", "판결 취소권", "주목, 모든 지상 보호 기동대, 현재 판결 취소권이 발효되었다. 임의로 극형을 집행할 수 있다.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "집계 불일치", "거주민 주목: 해당 구역에서 집계 불일치가 감지되었다. 시민 보호 기동대에게 협조하면 전체 구역에 사례가 선사된다.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav", true)
Schema.voices.Add("Dispatch", "임무 완수 실패", "지상 병력 주목, 임무 완수 실패는 곧 외계로 영구히 추방되는 처벌로 연결된다. 코드 강조: 희생, 응집, 탄압.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav", true)
Schema.voices.Add("Dispatch", "엑소젠", "위험한 엑소젠 침입을 확인했다. 공공 감시대 증원 병력을 긴급 출동, 접근 중이다. 증원 대기.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav", true)
Schema.voices.Add("Dispatch", "감염", "거주민 주목, 이 구역에는 잠재적인 시민 감염의 위험이 내포돼 있다. 신고하고, 협조하고, 결집하라.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav", true)
Schema.voices.Add("Dispatch", "사회 반란 레벨5", "주목, 당신은 사회 반란 레벨 5, 사회 반란 레벨 5로 고발되었다. 기피하지 말고 즉시 평결을 받으라.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav", true)
Schema.voices.Add("Dispatch", "기피 대상", "보호 기동대 주목, 이 지역에 기피 대상 움직임이 감지되고 있다. 대응, 격리, 조사.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "미확인", "주목, 임시 미확인된 용의자로 분류되었다. 불이익을 받지 않으려면 즉시 시민 보호 기동대에게 신분을 확인하라.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "소요 사태", "지역 시민 주목, 현재 소요 사태 진압 절차 코드가 발효되었다. 코드: 접종, 보호, 진압. 코드: 압력, 무력, 격리.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav", true)
Schema.voices.Add("Dispatch", "소요 사태2", "경보, 지상 지역 시민 보호 기동대. 해당 지역에 소요 사태가 감지되었다. 결집, 집행, 진압.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav", true)

Schema.voices.Add("Breencast", "협조자", "최근에 일부 시민들이 비열하다는 뜻으로 저를 협조자라고 부른다는 이야기를 들었습니다.", "vo/breencast/br_collaboration01.wav", true)
Schema.voices.Add("Breencast", "협조자2", "묻겠습니다. 협조보다 더 위대한 노력이 있습니까?", "vo/breencast/br_collaboration02.wav", true)
Schema.voices.Add("Breencast", "협조자3", "인류가 여태껏 한번도 겪은 적 없는 현재 상황에서, 협조를 거부하는 것은 바로 성장을 거부하는 것입니다.", "vo/breencast/br_collaboration03.wav", true)
Schema.voices.Add("Breencast", "협조자4", "폐어가 공기로 숨쉬는 것을 거부했나요? 아닙니다.", "vo/breencast/br_collaboration04.wav", true)
Schema.voices.Add("Breencast", "협조자6", "우리의 종말이 삼엽충과 같아서야 되겠습니까?", "vo/breencast/br_collaboration06.wav", true)
Schema.voices.Add("Breencast", "협조자7", "인류의 모든 업적이 화석이 되어 하찮은 혈암과 영겁의 진흙 사이에 묻히는 운명을 지켜보고만 계시겠습니까? 여러분이 바라는 것이 진정 이것이였나요?", "vo/breencast/br_collaboration07.wav", true)
Schema.voices.Add("Breencast", "협조자8", "우리의 운명을 받아들이려면 우리는 보다 높은 이상을 갈망해야 합니다. 우리는 더이상 요람에 머물러서는 안됩니다. 전 우주가 눈앞에 펼쳐져 있는데 어머님의 모유로 만족할 수는 없습니다.", "vo/breencast/br_collaboration08.wav", true)
Schema.voices.Add("Breencast", "협조자9", "그리고 소인배들이 콤바인이라 부르는 우주 공동체만이 그 해답을 줄 수 있습니다.", "vo/breencast/br_collaboration09.wav", true)
Schema.voices.Add("Breencast", "협조자10", "따라서, 인정하겠습니다. 저는 협조자입니다. 통일이라는 혜택을 얻으려면 우리 모두 자진해서 적극 협조해야 합니다.", "vo/breencast/br_collaboration10.wav", true)
Schema.voices.Add("Breencast", "협조자11", "그러면 얻을 것입니다.", "vo/breencast/br_collaboration11.wav", true)
Schema.voices.Add("Breencast", "본능", "최근에 받은 편지를 읽어드리겠습니다. '박사님께, 무슨 이유로 콤바인이 우리의 생식 욕구를 억제한 것인가요?' 감사합니다. 고민 많은 시민.", "vo/breencast/br_instinct01.wav", true)
Schema.voices.Add("Breencast", "본능2", "잘 읽었습니다. 물론 이 질문에는 기본적인 생리적 욕구와 아울러 이와 연관된 인간의 미래에 대한 모든 희망과 우려도 함축되어 있습니다.", "vo/breencast/br_instinct02.wav", true)
Schema.voices.Add("Breencast", "본능3", "또한 이런 의구심들이 느껴집니다. 우리 은인들은 우리에게 이로운 것이 무엇인지 알고 있습니까? 인류 전체에 영향을 미치는 결정을 할 자격이 있습니까? 억제 장치를 해제하고 다시 자녀를 낳을 수 있는 날은 옵니까?", "vo/breencast/br_instinct03.wav", true)
Schema.voices.Add("Breencast", "본능4", "이 분이 느끼는 수많은 의구심에 일일히 답하는 것보다, 그 의구심에 내포된 불안에 대한 답변을 드리도록 하겠습니다.", "vo/breencast/br_instinct04.wav", true)
Schema.voices.Add("Breencast", "본능5", "먼저, 인류 역사상 최초로 영원한 생명의 꿈이 실현될 기회를 얻었습니다.", "vo/breencast/br_instinct05.wav", true)
Schema.voices.Add("Breencast", "본능6", "이에 따른 여파는 아주 복잡합니다. 즉, 인간의 유전 욕구에 대해 근본적인 개혁과 교정이 필요합니다.", "vo/breencast/br_instinct06.wav", true)
Schema.voices.Add("Breencast", "본능7", "또한, 우리가 지금까지 간직한 가치관과 전혀 다른 전망도 필요합니다.", "vo/breencast/br_instinct07.wav", true)
Schema.voices.Add("Breencast", "본능8", "저는 스스로, 진정한 적은 바로 본능이라는 사실에 힘을 얻곤 했습니다.", "vo/breencast/br_instinct08.wav", true)
Schema.voices.Add("Breencast", "본능9", "인류가 걸음마 시절에 있을 때 본능은 어머니였습니다.", "vo/breencast/br_instinct09.wav", true)
Schema.voices.Add("Breencast", "본능10", "나무로 무기를 만들고, 위태한 불 위에 음식을 만들고, 동굴 벽에 뛰어오르던 그림자에 깜짝 놀라 몸을 움츠리던 열악한 시절.", "vo/breencast/br_instinct10.wav", true)
Schema.voices.Add("Breencast", "본능11", "본능은 우리를 돌봐주고 안전하게 보호해 주었습니다.", "vo/breencast/br_instinct11.wav", true)
Schema.voices.Add("Breencast", "본능12", "그러나 본능에게는 암흑의 쌍둥이, 미신이 있습니다.", "vo/breencast/br_instinct12.wav", true)
Schema.voices.Add("Breencast", "본능13", "본능은 불합리한 충동과 밀접합니다. 이제 그 실체가 확실히 드러났습니다. 본능은 우리에게 필요한 존재가 아닙니다. 이제 본능과 싸울 최후의 전투를 준비해야 합니다.", "vo/breencast/br_instinct13.wav", true)
Schema.voices.Add("Breencast", "본능14", "본능은 인류에게 치명적입니다.", "vo/breencast/br_instinct14.wav", true)
Schema.voices.Add("Breencast", "본능15", "본능은 임의대로 폭군을 만들어 이에 대항하도록 부추깁니다.", "vo/breencast/br_instinct15.wav", true)
Schema.voices.Add("Breencast", "본능16", "본능은 우리가 모르는 것은 기회가 아닌, 위협이라고 말합니다.", "vo/breencast/br_instinct16.wav", true)
Schema.voices.Add("Breencast", "본능17", "본능은 은밀하게 발전으로부터 우리를 멀어지게 합니다.", "vo/breencast/br_instinct17.wav", true)
Schema.voices.Add("Breencast", "본능18", "따라서, 본능은 사라져야 합니다.", "vo/breencast/br_instinct18.wav", true)
Schema.voices.Add("Breencast", "본능19", "우리는 그 중, 가장 기본적인 욕구에 맞서 싸워야 합니다. 바로 번식 욕구입니다.", "vo/breencast/br_instinct19.wav", true)
Schema.voices.Add("Breencast", "본능20", "우리는 이런 욕구의 굴레에서 벗어날 수 있다는 사실에 감사해야 합니다.", "vo/breencast/br_instinct20.wav", true)
Schema.voices.Add("Breencast", "본능21", "그들은 스위치 하나로 우리 내면의 악마를 단 한번에 몰아내 주었습니다.", "vo/breencast/br_instinct21.wav", true)
Schema.voices.Add("Breencast", "본능22", "이런 본능을 극복할 능력이 없는 우리에게, 그들은 힘을 주었습니다.", "vo/breencast/br_instinct22.wav", true)
Schema.voices.Add("Breencast", "본능23", "우리 삶에 의미를 부여했습니다. 이제 우주로 눈을 돌리게 되었습니다.", "vo/breencast/br_instinct23.wav", true)
Schema.voices.Add("Breencast", "본능24", "우리가 더이상 본능을 필요로 하지 않는다는 것을 증명했을 때, 그날이 오면 억제 장치는 반드시 풀릴 것입니다. 이것은 진실입니..", "vo/breencast/br_instinct24.wav", true)
Schema.voices.Add("Breencast", "본능25", "그리고, 우리의 진화가 완성되는 그 날이 바로 눈앞에 펼쳐져 있습니다.", "vo/breencast/br_instinct25.wav", true)
Schema.voices.Add("Breencast", "환영", "17번 지구에 오신 것을 환영합니다.", "vo/breencast/br_welcome01.wav", true)
Schema.voices.Add("Breencast", "환영2", "귀하께서는 몇 안되는 훌륭한 도시로의 이전을 선택하셨거나, 선택받으셨습니다.", "vo/breencast/br_welcome02.wav", true)
Schema.voices.Add("Breencast", "환영3", "저는 17번 지구를 특별하게 생각해 왔습니다. 그래서 은인들이 마련해 준", "vo/breencast/br_welcome03.wav", true)
Schema.voices.Add("Breencast", "환영4", "이 아름다운 도시에 행정부를 설립하게 되었습니다.", "vo/breencast/br_welcome04.wav", true)
Schema.voices.Add("Breencast", "환영5", "저는 이곳의 한 시민이라는 사실이 자랑스럽습니다. 이곳에 거주하실 분이든, 또는 잠시 머물다 가실 손님이든", "vo/breencast/br_welcome05.wav", true)
Schema.voices.Add("Breencast", "환영6", "모두 다 환영합니다.", "vo/breencast/br_welcome06.wav", true)
Schema.voices.Add("Breencast", "환영7", "이곳은 안전합니다.", "vo/breencast/br_welcome07.wav", true)

Schema.voices.Add("CitizenMale", "실탄", "여기 실탄이요.", "vo/npc/male01/ammo03.wav")
Schema.voices.Add("CitizenMale", "실탄2", "실탄을 챙기세요.", "vo/npc/male01/ammo04.wav")
Schema.voices.Add("CitizenMale", "또시작", "또 시작이군.", "vo/npc/male01/answer01.wav")
Schema.voices.Add("CitizenMale", "안말려", "말리지 않을게.", "vo/npc/male01/answer02.wav")
Schema.voices.Add("CitizenMale", "나도", "나도.", "vo/npc/male01/answer03.wav")
Schema.voices.Add("CitizenMale", "생각마", "자꾸 생각하지 마.", "vo/npc/male01/answer04.wav")
Schema.voices.Add("CitizenMale", "나중에", "나중에 이야기해도 될까?", "vo/npc/male01/answer05.wav")
Schema.voices.Add("CitizenMale", "공감", "공감이야.", "vo/npc/male01/answer07.wav")
Schema.voices.Add("CitizenMale", "알아", "무슨 말인지 알아.", "vo/npc/male01/answer08.wav")
Schema.voices.Add("CitizenMale", "혼잣말", "또 혼잣말을 하는군.", "vo/npc/male01/answer09.wav")
Schema.voices.Add("CitizenMale", "목소리 커", "목소리가 너무 크다니까.", "vo/npc/male01/answer10.wav")
Schema.voices.Add("CitizenMale", "왜 몰라", "그걸 모르는 사람이 어디있나?", "vo/npc/male01/answer11.wav")
Schema.voices.Add("CitizenMale", "자꾸생각", "자꾸 그런 생각이 들어.", "vo/npc/male01/answer12.wav")
Schema.voices.Add("CitizenMale", "ㅇㅇ2", "듣고 있어.", "vo/npc/male01/answer13.wav")
Schema.voices.Add("CitizenMale", "마찬가지", "하, 나도 마찬가지야.", "vo/npc/male01/answer14.wav")
Schema.voices.Add("CitizenMale", "그럴수도", "한편으론 그럴수도 있지.", "vo/npc/male01/answer15.wav")
Schema.voices.Add("CitizenMale", "처음부터?", "처음부터 정말 그렇게 생각했어?", "vo/npc/male01/answer16.wav")
Schema.voices.Add("CitizenMale", "ㄷㅊ", "꼭 입 다물라고 말해야 알겠나?", "vo/npc/male01/answer17.wav")
Schema.voices.Add("CitizenMale", "집중3", "코 앞에 닥친 일에나 집중해.", "vo/npc/male01/answer18.wav")
Schema.voices.Add("CitizenMale", "집중", "일에 좀 집중하라고.", "vo/npc/male01/answer19.wav")
Schema.voices.Add("CitizenMale", "집중2", "마음이 다른 데 있군.", "vo/npc/male01/answer20.wav")
Schema.voices.Add("CitizenMale", "믿지마", "너무 믿지 마", "vo/npc/male01/answer21.wav")
Schema.voices.Add("CitizenMale", "넌몰라", "당신은 몰라.", "vo/npc/male01/answer22.wav")
Schema.voices.Add("CitizenMale", "ㅁㄹ", "모르겠는데?", "vo/npc/male01/answer23.wav")
Schema.voices.Add("CitizenMale", "나?2", "왜 나한태 말하지?", "vo/npc/male01/answer24.wav")
Schema.voices.Add("CitizenMale", "어때서", "그게 어때서.", "vo/npc/male01/answer25.wav")
Schema.voices.Add("CitizenMale", "똑똑하군", "그걸 알다니 정말 똑똑하군.", "vo/npc/male01/answer26.wav")
Schema.voices.Add("CitizenMale", "정말?", "하하하, 정말이야?", "vo/npc/male01/answer27.wav")
Schema.voices.Add("CitizenMale", "돈", "남들이 그렇게 말할 때마다 돈이 생겼으면 좋으련만.", "vo/npc/male01/answer28.wav")
Schema.voices.Add("CitizenMale", "뭘원해", "내가 어떻게 했으면 좋겠어.", "vo/npc/male01/answer29.wav")
Schema.voices.Add("CitizenMale", "나?", "나 말이야?", "vo/npc/male01/answer30.wav")
Schema.voices.Add("CitizenMale", "방지", "이런 말은 미연에 방지하는 게 좋아.", "vo/npc/male01/answer31.wav")
Schema.voices.Add("CitizenMale", "ㅇㅇ", "맞아.", "vo/npc/male01/answer32.wav")
Schema.voices.Add("CitizenMale", "동감", "전적으로 동감이야.", "vo/npc/male01/answer33.wav")
Schema.voices.Add("CitizenMale", "하와이", "하와이를 잊지 마.", "vo/npc/male01/answer34.wav")
Schema.voices.Add("CitizenMale", "여유찾아", "마음의 여유를 찾으라고.", "vo/npc/male01/answer35.wav")
Schema.voices.Add("CitizenMale", "처음아님", "처음은 아닐거야.", "vo/npc/male01/answer36.wav")
Schema.voices.Add("CitizenMale", "ㄹㅇ?", "정말 확실해?", "vo/npc/male01/answer37.wav")
Schema.voices.Add("CitizenMale", "상관마", "상관 마.", "vo/npc/male01/answer38.wav")
Schema.voices.Add("CitizenMale", "충분해", "그것으로 충분해.", "vo/npc/male01/answer39.wav")
Schema.voices.Add("CitizenMale", "처음있음", "뭐든지 처음은 있는 거라고.", "vo/npc/male01/answer40.wav")
Schema.voices.Add("CitizenMale", "뒤에있어", "뒤에 있어요!", "vo/npc/male01/behindyou01.wav")
Schema.voices.Add("CitizenMale", "바빠", "지금 바쁜 거 안보이십니까?", "vo/npc/male01/busy02.wav")
Schema.voices.Add("CitizenMale", "그거줘", "이봐 거기! 그것 좀 줘!", "vo/npc/male01/cit_dropper01.wav")
Schema.voices.Add("CitizenMale", "아래조심", "아래 조심해요!", "vo/npc/male01/cit_dropper04.wav")
Schema.voices.Add("CitizenMale", "기동대2", "보호 기동대다!", "vo/npc/male01/civilprotection01.wav")
Schema.voices.Add("CitizenMale", "콤바인", "콤바인!", "vo/npc/male01/combine01.wav")
Schema.voices.Add("CitizenMale", "장전엄호", "장전할 때 날 엄호해요.", "vo/npc/male01/coverwhilereload01.wav")
Schema.voices.Add("CitizenMale", "기동대", "기동대!", "vo/npc/male01/cps01.wav")
Schema.voices.Add("CitizenMale", "뭔가 할", "뭔가 할 수 있는 게 없을까요?", "vo/npc/male01/doingsomething.wav")
Schema.voices.Add("CitizenMale", "공평하게", "공평하게 합시다.", "vo/npc/male01/evenodds.wav")
Schema.voices.Add("CitizenMale", "실례", "실례해요.", "vo/npc/male01/excuseme01.wav")
Schema.voices.Add("CitizenMale", "훌륭해요", "훌륭해요.", "vo/npc/male01/fantastic01.wav")
Schema.voices.Add("CitizenMale", "해냈군요", "해냈군요.", "vo/npc/male01/finally.wav")
Schema.voices.Add("CitizenMale", "엎드려", "엎드려요!", "vo/npc/male01/getdown02.wav")
Schema.voices.Add("CitizenMale", "언제출발", "언제 출발합니까?", "vo/npc/male01/getgoingsoon.wav")
Schema.voices.Add("CitizenMale", "나가", "당장 여기서 나가요!", "vo/npc/male01/gethellout.wav")
Schema.voices.Add("CitizenMale", "맙소사", "맙소사.", "vo/npc/male01/goodgod.wav")
Schema.voices.Add("CitizenMale", "어쩌죠", "이제 어쩌죠?", "vo/npc/male01/gordead_ans01.wav")
Schema.voices.Add("CitizenMale", "안풀림", "왜 이렇게 일이 잘 풀리나 했어.", "vo/npc/male01/gordead_ans02.wav")
Schema.voices.Add("CitizenMale", "ㅇㅇ3", "그러게.", "vo/npc/male01/gordead_ans03.wav")
Schema.voices.Add("CitizenMale", "세상에", "오, 세상에.", "vo/npc/male01/gordead_ans04.wav")
Schema.voices.Add("CitizenMale", "ㄴㄴ", "아, 안돼.", "vo/npc/male01/gordead_ans05.wav")
Schema.voices.Add("CitizenMale", "ㄴㄴ2", "제발, 안돼.", "vo/npc/male01/gordead_ans06.wav")
Schema.voices.Add("CitizenMale", "농담하지마", "지금 농담같은 걸 하면 가만두지 않겠어.", "vo/npc/male01/gordead_ans07.wav")
Schema.voices.Add("CitizenMale", "묻을까", "여기에 묻을까?", "vo/npc/male01/gordead_ans08.wav")
Schema.voices.Add("CitizenMale", "모두알려줘", "모두에게 알려주세요.", "vo/npc/male01/gordead_ans10.wav")
Schema.voices.Add("CitizenMale", "소용없어", "무슨 소용이야.", "vo/npc/male01/gordead_ans11.wav")
Schema.voices.Add("CitizenMale", "쓸데없어", "쓸데없는 짓이야.", "vo/npc/male01/gordead_ans12.wav")
Schema.voices.Add("CitizenMale", "희망없어", "희망이 없어.", "vo/npc/male01/gordead_ans13.wav")
Schema.voices.Add("CitizenMale", "우린끝났어", "우린 끝났어.", "vo/npc/male01/gordead_ans14.wav")
Schema.voices.Add("CitizenMale", "어쩌지2", "자, 이제 어쩌지?", "vo/npc/male01/gordead_ans15.wav")
Schema.voices.Add("CitizenMale", "처음아님2", "처음이 아니잖아, 괜찮을 거야.", "vo/npc/male01/gordead_ans18.wav")
Schema.voices.Add("CitizenMale", "토나와", "토할 것 같아.", "vo/npc/male01/gordead_ans19.wav")
Schema.voices.Add("CitizenMale", "크로우바", "누가 크로우바를 좀 가져가요.", "vo/npc/male01/gordead_ans20.wav")
Schema.voices.Add("CitizenMale", "죽었어", "죽었어.", "vo/npc/male01/gordead_ques01.wav")
Schema.voices.Add("CitizenMale", "끔찍", "끔찍하군.", "vo/npc/male01/gordead_ques02.wav")
Schema.voices.Add("CitizenMale", "그럴리가", "그럴리가 없어.", "vo/npc/male01/gordead_ques06.wav")
Schema.voices.Add("CitizenMale", "죽었어2", "봐요, 죽었어.", "vo/npc/male01/gordead_ques07.wav")
Schema.voices.Add("CitizenMale", "큰일", "큰일이야.", "vo/npc/male01/gordead_ques10.wav")
Schema.voices.Add("CitizenMale", "천하무적", "천하무적인줄 알았어.", "vo/npc/male01/gordead_ques11.wav")
Schema.voices.Add("CitizenMale", "희망없어2", "이게 마지막 희망이였어?", "vo/npc/male01/gordead_ques13.wav")
Schema.voices.Add("CitizenMale", "끝날수없어", "이렇게 끝날 순 없어.", "vo/npc/male01/gordead_ques14.wav")
Schema.voices.Add("CitizenMale", "어쩌지", "이제 어쩌지?", "vo/npc/male01/gordead_ques16.wav")
Schema.voices.Add("CitizenMale", "남길말", "남기고 싶은 말이라도?", "vo/npc/male01/gordead_ques17.wav")
Schema.voices.Add("CitizenMale", "잡았다", "잡았다!", "vo/npc/male01/gotone01.wav")
Schema.voices.Add("CitizenMale", "장전", "장전해야 해요!", "vo/npc/male01/gottareload01.wav")
Schema.voices.Add("CitizenMale", "헬기", "무장헬기!", "vo/npc/male01/gunship02.wav")
Schema.voices.Add("CitizenMale", "맨핵", "맨핵!", "vo/npc/male01/hacks01.wav")
Schema.voices.Add("CitizenMale", "헤드크랩", "헤드크랩!", "vo/npc/male01/headcrabs01.wav")
Schema.voices.Add("CitizenMale", "이쪽3", "이쪽이다!", "vo/npc/male01/headsup01.wav")
Schema.voices.Add("CitizenMale", "메드킷", "메드 키트를 받아요.", "vo/npc/male01/health01.wav")
Schema.voices.Add("CitizenMale", "메드킷2", "메드 키트를 써봐요.", "vo/npc/male01/health04.wav")
Schema.voices.Add("CitizenMale", "보충해", "여기요, 보충 좀 하세요", "vo/npc/male01/health05.wav")
Schema.voices.Add("CitizenMale", "도와줘", "도와줘요!", "vo/npc/male01/help01.wav")
Schema.voices.Add("CitizenMale", "맨핵3", "맨핵이 온다!", "vo/npc/male01/hearcomehacks01.wav")
Schema.voices.Add("CitizenMale", "그들온다", "그들이 와요!", "vo/npc/male01/heretheycome01.wav")
Schema.voices.Add("CitizenMale", "도우러온줄", "우릴 도우러 온 줄 알았다고요.", "vo/npc/male01/heretohelp01.wav")
Schema.voices.Add("CitizenMale", "배맞음", "으허억, 배를 맞았어.", "vo/npc/male01/hitingut01.wav")
Schema.voices.Add("CitizenMale", "자리사수", "여기서 이 자리를 사수할게요.", "vo/npc/male01/holddownspot01.wav")
Schema.voices.Add("CitizenMale", "여기남음", "여기 남을게요.", "vo/npc/male01/illstayhere01.wav")
Schema.voices.Add("CitizenMale", "다침", "다쳤어요!", "vo/npc/male01/imhurt01.wav")
Schema.voices.Add("CitizenMale", "여기남음2", "여기 남겠어요.", "vo/npc/male01/imstickinghere01.wav")
Schema.voices.Add("CitizenMale", "온다", "온다!", "vo/npc/male01/incoming02.wav")
Schema.voices.Add("CitizenMale", "맨핵2", "맨핵이다!", "vo/npc/male01/itsamanhack01.wav")
Schema.voices.Add("CitizenMale", "안내해요2", "어서 안내해요!", "vo/npc/male01/leadtheway01.wav")
Schema.voices.Add("CitizenMale", "안내해요", "안내해요!", "vo/npc/male01/leadtheway02.wav")
Schema.voices.Add("CitizenMale", "ㄱㄱ", "가요!", "vo/npc/male01/letsgo01.wav")
Schema.voices.Add("CitizenMale", "맛어때", "맛이 어때!", "vo/npc/male01/likethat.wav")
Schema.voices.Add("CitizenMale", "내구역", "여긴 내 구역이고, 끝까지 지킬 겁니다.", "vo/npc/male01/littlecorner01.wav")
Schema.voices.Add("CitizenMale", "내팔", "으헉, 내 팔.", "vo/npc/male01/myarm01.wav")
Schema.voices.Add("CitizenMale", "배맞음2", "으허헉, 배아!", "vo/npc/male01/mygut02.wav")
Schema.voices.Add("CitizenMale", "내다리", "으헉, 내 다리.", "vo/npc/male01/myleg01.wav")
Schema.voices.Add("CitizenMale", "굿", "좋아.", "vo/npc/male01/nice.wav")
Schema.voices.Add("CitizenMale", "ㄴㄴ3", "안돼, 안돼!", "vo/npc/male01/no01.wav")
Schema.voices.Add("CitizenMale", "생각과다름", "내가 생각했던 사람이 아니군요.", "vo/npc/male01/notthemanithought01.wav")
Schema.voices.Add("CitizenMale", "네", "네.", "vo/npc/male01/ok01.wav")
Schema.voices.Add("CitizenMale", "ㅇㅋ2", "좋아요.", "vo/npc/male01/ok02.wav")
Schema.voices.Add("CitizenMale", "준비완료", "네, 준비됬어요.", "vo/npc/male01/okimready01.wav")
Schema.voices.Add("CitizenMale", "내꺼", "내 꺼, 그리고 또 내 꺼.", "vo/npc/male01/oneforme.wav")
Schema.voices.Add("CitizenMale", "ㅂㅋ", "좀 지나갈게요.", "vo/npc/male01/outofyourway02.wav")
Schema.voices.Add("CitizenMale", "이쪽", "이쪽이예요.", "vo/npc/male01/overhere01.wav")
Schema.voices.Add("CitizenMale", "저쪽", "저쪽이요.", "vo/npc/male01/overthere01.wav")
Schema.voices.Add("CitizenMale", "실례2", "아, 실례합니다.", "vo/npc/male01/pardonme01.wav")
Schema.voices.Add("CitizenMale", "잠깐", "잠깐만요.", "vo/npc/male01/pardonme02.wav")
Schema.voices.Add("CitizenMale", "전쟁안끝나", "이 전쟁이 끝날 것 같지가 않아.", "vo/npc/male01/question01.wav")
Schema.voices.Add("CitizenMale", "보험팔래", "보험이나 팔러 다니면 좋겠다는 생각이 드는군.", "vo/npc/male01/question02.wav")
Schema.voices.Add("CitizenMale", "기대없음", "더이상 기대도 없어.", "vo/npc/male01/question03.wav")
Schema.voices.Add("CitizenMale", "다끝나면", "모든 게 다 끝나면 난... 아, 쓸데없는 소리.", "vo/npc/male01/question04.wav")
Schema.voices.Add("CitizenMale", "데자부", "오, 데자부야.", "vo/npc/male01/question05.wav")
Schema.voices.Add("CitizenMale", "치즈먹는상상", "때론 치즈를 먹는 상상을 해.", "vo/npc/male01/question06.wav")
Schema.voices.Add("CitizenMale", "자유의냄새", "느껴져? 자유의 냄새라고.", "vo/npc/male01/question07.wav")
Schema.voices.Add("CitizenMale", "브린박사", "브린 박사, 잡히기만 해봐.", "vo/npc/male01/question08.wav")
Schema.voices.Add("CitizenMale", "배고파2", "뭐든 닥치는대로 먹고 싶군.", "vo/npc/male01/question09.wav")
Schema.voices.Add("CitizenMale", "이날", "이 날이 결국 왔다니 믿기지가 않아.", "vo/npc/male01/question10.wav")
Schema.voices.Add("CitizenMale", "변수", "이건 계획에 없었던 게 분명해.", "vo/npc/male01/question11.wav")
Schema.voices.Add("CitizenMale", "설상가상", "상황이 좋아지기는 커녕 더 나빠지는 것 같아.", "vo/npc/male01/question12.wav")
Schema.voices.Add("CitizenMale", "내인생", "내 인생을 다시 살 수만 있다면.", "vo/npc/male01/question13.wav")
Schema.voices.Add("CitizenMale", "안말해", "지금 무슨 생각이 드는지는 말하지 않을거야.", "vo/npc/male01/question14.wav")
Schema.voices.Add("CitizenMale", "ㄲㅈ", "나를 집요하게 쫒아다니지는 않겠지.", "vo/npc/male01/question15.wav")
Schema.voices.Add("CitizenMale", "기회다", "결국 기회는 왔어.", "vo/npc/male01/question16.wav")
Schema.voices.Add("CitizenMale", "느껴져", "느껴져? 난 느껴져.", "vo/npc/male01/question17.wav")
Schema.voices.Add("CitizenMale", "못느껴", "더이상 느낄 수가 없어.", "vo/npc/male01/question18.wav")
Schema.voices.Add("CitizenMale", "샤워", "마지막으로 샤워한 게 언제인지 기억조차 안나.", "vo/npc/male01/question19.wav")
Schema.voices.Add("CitizenMale", "끔찍한기억", "훗날... 끔찍한 기억으로만 남게 되겠지.", "vo/npc/male01/question20.wav")
Schema.voices.Add("CitizenMale", "상황별로", "꼭 그런 건 아니지만 상황이 별로 안좋아.", "vo/npc/male01/question21.wav")
Schema.voices.Add("CitizenMale", "무시ㄴ", "내 생각은 다들 무시하는거야?", "vo/npc/male01/question22.wav")
Schema.voices.Add("CitizenMale", "휘파람", "이 음이 머리에서 떠나질 않아. *(휘파람)*", "vo/npc/male01/question23.wav")
Schema.voices.Add("CitizenMale", "매일똑같아", "매일매일이 똑같다는 것만 알 뿐이지.", "vo/npc/male01/question25.wav")
Schema.voices.Add("CitizenMale", "ㅁㅊ", "말도 안돼.", "vo/npc/male01/question26.wav")
Schema.voices.Add("CitizenMale", "토나와2", "먹은 게 잘못된 것 같아.", "vo/npc/male01/question27.wav")
Schema.voices.Add("CitizenMale", "배고파", "배가 고프군.", "vo/npc/male01/question28.wav")
Schema.voices.Add("CitizenMale", "연애", "모두 다 끝나면 연애를 할거야.", "vo/npc/male01/question29.wav")
Schema.voices.Add("CitizenMale", "아이들", "아이들이 이 모습을 보지 못해서 다행이야.", "vo/npc/male01/question30.wav")
Schema.voices.Add("CitizenMale", "ㄹㄷ", "준비됬습니다!", "vo/npc/male01/readywhenyouare01.wav")
Schema.voices.Add("CitizenMale", "ㅌㅌ", "도망쳐요!", "vo/npc/male01/runforyourlife01.wav")
Schema.voices.Add("CitizenMale", "스캐너", "스캐너!", "vo/npc/male01/scanners01.wav")
Schema.voices.Add("CitizenMale", "ㅈㅅ", "죄송해요.", "vo/npc/male01/sorry01.wav")
Schema.voices.Add("CitizenMale", "ㅇㅋ", "알겠습니다.", "vo/npc/male01/squad_affirm01.wav")
Schema.voices.Add("CitizenMale", "뭐든지", "뭐든지요.", "vo/npc/male01/squad_affirm03.wav")
Schema.voices.Add("CitizenMale", "ㅇㅋㄱ", "좋아요, 갑니다.", "vo/npc/male01/squad_affirm04.wav")
Schema.voices.Add("CitizenMale", "저도요", "저도요.", "vo/npc/male01/squad_affirm05.wav")
Schema.voices.Add("CitizenMale", "본전", "믿져야 본전이죠.", "vo/npc/male01/squad_affirm06.wav")
Schema.voices.Add("CitizenMale", "드디어", "드디어 오는군요.", "vo/npc/male01/squad_approach02.wav")
Schema.voices.Add("CitizenMale", "우리쪽", "우리 쪽으로.", "vo/npc/male01/squad_approach03.wav")
Schema.voices.Add("CitizenMale", "이쪽2", "이쪽이야.", "vo/npc/male01/squad_away01.wav")
Schema.voices.Add("CitizenMale", "여기로", "여기로.", "vo/npc/male01/squad_away02.wav")
Schema.voices.Add("CitizenMale", "어서2", "자, 어서요.", "vo/npc/male01/squad_follow02.wav")
Schema.voices.Add("CitizenMale", "ㄱㄷ", "기다려요.", "vo/npc/male01/squad_reinforce_group04.wav")
Schema.voices.Add("CitizenMale", "ㄱㄷ2", "기다려주세요.", "vo/npc/male01/squad_reinforce_single04.wav")
Schema.voices.Add("CitizenMale", "스트라이더", "스트라이더!", "vo/npc/male01/strider.wav")
Schema.voices.Add("CitizenMale", "ㅌㅌ2", "뛰어요!", "vo/npc/male01/strider_run.wav")
Schema.voices.Add("CitizenMale", "엄호", "엄호해요!", "vo/npc/male01/takecover02.wav")
Schema.voices.Add("CitizenMale", "괜찮은데", "이거 괜찮은데?", "vo/npc/male01/thislldonicely02.wav")
Schema.voices.Add("CitizenMale", "저기", "저기!", "vo/npc/male01/upthere01.wav")
Schema.voices.Add("CitizenMale", "허튼소리", "허튼 소리하지 마.", "vo/npc/male01/vanswer01.wav")
Schema.voices.Add("CitizenMale", "보르티ㅅㅂ", "젠장할, 보르티곤트.", "vo/npc/male01/vanswer02.wav")
Schema.voices.Add("CitizenMale", "어떻게하지", "어떻게 처리해야 할 지 모르겠어.", "vo/npc/male01/vanswer03.wav")
Schema.voices.Add("CitizenMale", "내가처리할까", "내가 처리할까?", "vo/npc/male01/vanswer04.wav")
Schema.voices.Add("CitizenMale", "뭐래", "알아듣게 말해.", "vo/npc/male01/vanswer05.wav")
Schema.voices.Add("CitizenMale", "나한테서", "나한테서 들었잖아.", "vo/npc/male01/vanswer06.wav")
Schema.voices.Add("CitizenMale", "참아", "그러니까 우리가 참는거지.", "vo/npc/male01/vanswer07.wav")
Schema.voices.Add("CitizenMale", "참아2", "혼자라면 더 잘 참았을거야.", "vo/npc/male01/vanswer08.wav")
Schema.voices.Add("CitizenMale", "말되네", "오, 그거 말 되네.", "vo/npc/male01/vanswer09.wav")
Schema.voices.Add("CitizenMale", "이해안됨", "나에게 문제가 있는 것 같아. 거의 이해했는데 말이야.", "vo/npc/male01/vanswer10.wav")
Schema.voices.Add("CitizenMale", "보르티익숙함", "보르티에게 좀 익숙해졌어.", "vo/npc/male01/vanswer11.wav")
Schema.voices.Add("CitizenMale", "보르티철학", "보르티 철학은 없어.", "vo/npc/male01/vanswer12.wav")
Schema.voices.Add("CitizenMale", "그만4", "그만해. 못참겠군.", "vo/npc/male01/vanswer13.wav")
Schema.voices.Add("CitizenMale", "헛수고", "내가 뭘 바라고 이 일을 했지?", "vo/npc/male01/vanswer14.wav")
Schema.voices.Add("CitizenMale", "보지마", "그렇게 쳐다보지 마.", "vo/npc/male01/vquestion01.wav")
Schema.voices.Add("CitizenMale", "적응안됨", "절대 익숙해질 수 없는 것도 있어.", "vo/npc/male01/vquestion02.wav")
Schema.voices.Add("CitizenMale", "살아남음", "지금까지 어떻게 살아남을 수 있었는지 모르겠군.", "vo/npc/male01/vquestion03.wav")
Schema.voices.Add("CitizenMale", "당신누구", "당신과 어떻게 같이 있게 됬는지 모르겠어.", "vo/npc/male01/vquestion04.wav")
Schema.voices.Add("CitizenMale", "보르티ㄱㅊ", "괜찮아, 보르티.", "vo/npc/male01/vquestion05.wav")
Schema.voices.Add("CitizenMale", "보르티충분함", "보르티면 충분해.", "vo/npc/male01/vquestion06.wav")
Schema.voices.Add("CitizenMale", "보르티친구", "보르티와 친구가 될 지 정말 몰랐어.", "vo/npc/male01/vquestion07.wav")
Schema.voices.Add("CitizenMale", "ㄱㄷ?", "누굴 기다려요?", "vo/npc/male01/waitingsomebody.wav")
Schema.voices.Add("CitizenMale", "조심", "조심해요!", "vo/npc/male01/watchout.wav")
Schema.voices.Add("CitizenMale", "조심2", "조심하라구요!", "vo/npc/male01/watchwhat.wav")
Schema.voices.Add("CitizenMale", "믿었음", "우린 믿었다구요.", "vo/npc/male01/wetrustedyou01.wav")
Schema.voices.Add("CitizenMale", "이런", "이런.", "vo/npc/male01/whoops01.wav")
Schema.voices.Add("CitizenMale", "장전해", "장전하세요.", "vo/npc/male01/youdbetterreload01.wav")
Schema.voices.Add("CitizenMale", "좀비", "좀비다!", "vo/npc/male01/zombies01.wav")
Schema.voices.Add("CitizenMale", "철수중4", "어서 가세요. 이제 여길 없애야 해요.", "vo/canals/male01/gunboat_breakcamp.wav")
Schema.voices.Add("CitizenMale", "끝장내", "그들을 끝장내주세요.", "vo/canals/male01/gunboat_giveemhell.wav")
Schema.voices.Add("CitizenMale", "철수중3", "서둘러야 합니다. 이 캠프를 정리하고 여기서 나가야 합니다.", "vo/canals/male01/gunboat_hurry.wav")
Schema.voices.Add("CitizenMale", "철수중2", "정말 잘 오셨습니다. 저들에게 들키기 전에 어서 여길 빠져나가야 해요.", "vo/canals/male01/gunboat_justintime.wav")
Schema.voices.Add("CitizenMale", "어서3", "어서 움직입시다! 우리를 노리기 전에 여기를 떠나야 합니다!", "vo/canals/male01/gunboat_moveone.wav")
Schema.voices.Add("CitizenMale", "보트", "보트는 여기 두시면 됩니다. 안전해요.", "vo/canals/male01/gunboat_parkboat.wav")
Schema.voices.Add("CitizenMale", "철수중", "딱 맞춰 오셨어요. 콤바인이 우리를 잡으러 오기 전에 여길 떠나야 해서, 지금 막 철수하려던 중이였습니다.", "vo/canals/male01/gunboat_pullout.wav")
Schema.voices.Add("CitizenMale", "어서", "어서요!", "vo/canals/male01/stn6_go_nag02.wav")
Schema.voices.Add("CitizenMale", "온다2", "저기 온다!", "vo/canals/male01/stn6_incoming.wav")
Schema.voices.Add("CitizenMale", "포탄공격", "포탄 공격이다!", "vo/canals/male01/stn6_shellingus.wav")
Schema.voices.Add("CitizenMale", "드롭십2", "아, 이런. 드롭십이 온다!", "vo/coast/barn/male01/crapships.wav")
Schema.voices.Add("CitizenMale", "차버려", "차를 버려야 합니다. 그들이 지금 차를 찾고 있어요.", "vo/coast/barn/male01/ditchcar.wav")
Schema.voices.Add("CitizenMale", "드롭십등대", "저기 등대에 드롭십이 있다!", "vo/coast/barn/male01/drop_lite.wav")
Schema.voices.Add("CitizenMale", "드롭십길", "드롭십, 길 너머로 온다!", "vo/coast/barn/male01/drop_road.wav")
Schema.voices.Add("CitizenMale", "저쪽ㄱ", "저쪽으로 쭉 가세요. 조심하시고요.", "vo/coast/barn/male01/exit_watchstep.wav")
Schema.voices.Add("CitizenMale", "차숨겨", "빨리 차를 헛간에 숨겨요!", "vo/coast/barn/male01/getcarinbarn.wav")
Schema.voices.Add("CitizenMale", "차넣어", "차를 차고에 넣어요.", "vo/coast/barn/male01/getcaringarage.wav")
Schema.voices.Add("CitizenMale", "벗어나", "길에서 벗어나요!", "vo/coast/barn/male01/getoffroad01.wav")
Schema.voices.Add("CitizenMale", "걸어가", "저희가 차에서 무기를 가져올게요. 지금부터는 걸어서 가셔야 합니다.", "vo/coast/barn/male01/gettauoff.wav")
Schema.voices.Add("CitizenMale", "드롭십", "드롭십 출현!", "vo/coast/barn/male01/incomingdropship.wav")
Schema.voices.Add("CitizenMale", "헬기2", "무장 헬기다!", "vo/coast/barn/male01/lite_gunship01.wav")
Schema.voices.Add("CitizenMale", "넣어", "거기에 넣어요!", "vo/coast/barn/male01/parkit.wav")
Schema.voices.Add("CitizenMale", "페로포드", "페로포드의 효능은 제가 장담합니다.", "vo/coast/bugbait/male01/pheropod_nag02.wav")
Schema.voices.Add("CitizenMale", "개미귀신끝", "개미귀신들이 더는 괴롭히지 않을 겁니다.", "vo/coast/bugbait/male01/pheropod_nag03.wav")
Schema.voices.Add("CitizenMale", "굿2", "우후우! 좋아! 야!", "vo/coast/odessa/male01/nlo_cheer01.wav")
Schema.voices.Add("CitizenMale", "굿3", "우후우!", "vo/coast/odessa/male01/nlo_cheer02.wav")
Schema.voices.Add("CitizenMale", "굿4", "아하하하하! 좋아! 아하하하!", "vo/coast/odessa/male01/nlo_cheer03.wav")
Schema.voices.Add("CitizenMale", "굿5", "야! 하하! 우후!", "vo/coast/odessa/male01/nlo_cheer04.wav")
Schema.voices.Add("CitizenMale", "게이트2", "여기로 차를 가져오세요. 게이트를 열겠습니다.", "vo/coast/odessa/male01/nlo_citizen_bringcar.wav")
Schema.voices.Add("CitizenMale", "운전조심", "조심해서 모세요.", "vo/coast/odessa/male01/nlo_citizen_drivesafe.wav")
Schema.voices.Add("CitizenMale", "지하실", "어서 지하실로 가셔야 합니다. 언제 공격이 시작될 지 몰라요.", "vo/coast/odessa/male01/nlo_citizen_greet01.wav")
Schema.voices.Add("CitizenMale", "시간없음", "여기서 꾸물거릴 시간이 없어요. 콤바인이 접근해 오고 있습니다.", "vo/coast/odessa/male01/nlo_citizen_greet03.wav")
Schema.voices.Add("CitizenMale", "지하실2", "어서 지하실로 가세요! 지금 저들이 공격해오면 모든 사람들이 위험해진다구요!", "vo/coast/odessa/male01/nlo_citizen_greet04.wav")
Schema.voices.Add("CitizenMale", "게이트3", "차에 타세요. 제가 게이트를 열겠습니다.", "vo/coast/odessa/male01/nlo_getyourjeep.wav")
Schema.voices.Add("CitizenMale", "차타", "차에 타세요. 걸어서는 먼 길을 갈 수 없습니다.", "vo/coast/odessa/male01/nlo_yourcarsir.wav")
Schema.voices.Add("CitizenMale", "반갑", "만나서 반갑습니다.", "vo/eli_lab/airlock_cit01.wav")
Schema.voices.Add("CitizenMale", "얼른가", "얼른 가보십시오.", "vo/eli_lab/airlock_cit02.wav")
Schema.voices.Add("CitizenMale", "지뢰", "지뢰 파편을 조심해요! 여기저기 널려있어요!", "vo/streetwar/barricade/male01/c17_05_hoppers.wav")
Schema.voices.Add("CitizenMale", "ㅂㅋ2", "지나가게 해줘요!", "vo/streetwar/barricade/male01/c17_05_letusthru.wav")
Schema.voices.Add("CitizenMale", "지뢰2", "지뢰 파편을 치워버리지 마세요! 지뢰 파편을 모아두었다가 필요한 곳에 박아서 사용할 수 있어요!", "vo/streetwar/barricade/male01/c17_05_minehelp2.wav")
Schema.voices.Add("CitizenMale", "게이트", "게이트를 열어요!", "vo/streetwar/barricade/male01/c17_05_opengate.wav")
Schema.voices.Add("CitizenMale", "꺼내줘", "이봐요! 우릴 좀 꺼내줘요!", "vo/streetwar/nexus/male01/c17_10_letusout.wav")
Schema.voices.Add("CitizenMale", "기념비", "말 기념비로 가요!", "vo/streetwar/rubble/male01/d3_c17_13_horse01.wav")
Schema.voices.Add("CitizenMale", "기념비2", "말 기념비에 도착해야 되요.", "vo/streetwar/rubble/male01/d3_c17_13_horse01.wav")
Schema.voices.Add("CitizenMale", "스나이퍼", "도와줘요! 이 아래가 더 안전한 줄 알았어요. 여기가 이렇게 위험한 줄 생각도 못했어요. 몇 사람들은 스나이퍼들이 있다는 걸 알면서도 위험을 감수하고 올라갔어요. 아마 아직도 위에 있을 거예요.", "vo/streetwar/sniper/male01/c17_09_cellar.wav")
Schema.voices.Add("CitizenMale", "버텨", "조금만 더 버티세요. 거의 다 됬어요!", "vo/streetwar/tunnel/male01/c17_06_det02.wav")
Schema.voices.Add("CitizenMale", "하나남음", "좋아, 하나 남았습니다.", "vo/streetwar/tunnel/male01/c17_06_det03.wav")
Schema.voices.Add("CitizenMale", "폭발", "물러서요! 폭발시킵니다!", "vo/streetwar/tunnel/male01/c17_06_det04.wav")
Schema.voices.Add("CitizenMale", "이쪽으로", "이쪽으로 오십시오. 어서요!", "vo/streetwar/tunnel/male01/c17_06_det05.wav")
Schema.voices.Add("CitizenMale", "문열어", "이봐, 나야. 문 열어.", "vo/streetwar/tunnel/male01/c17_06_password01.wav")
Schema.voices.Add("CitizenMale", "암호2", "암호를 대.", "vo/streetwar/tunnel/male01/c17_06_password02.wav")
Schema.voices.Add("CitizenMale", "암호", "암호.", "vo/streetwar/tunnel/male01/c17_06_password03.wav")
Schema.voices.Add("CitizenMale", "들어와", "들어와.", "vo/streetwar/tunnel/male01/c17_06_password04.wav")
Schema.voices.Add("CitizenMale", "지나가", "자, 어서 지나가요.", "vo/streetwar/tunnel/male01/c17_06_plank01.wav")
Schema.voices.Add("CitizenMale", "여기남음2", "다른 사람이 지나갈 지도 모르니 전 여기 있어야 해요.", "vo/streetwar/tunnel/male01/c17_06_plank02.wav")
Schema.voices.Add("CitizenMale", "제때", "여긴 엉망이군요. 그래도 제 때에 맞춰 오셔서 다행이예요.", "vo/streetwar/tunnel/male01/c17_06_post_det02.wav")
Schema.voices.Add("CitizenMale", "해냈군요2", "정말 해내셨군요. 그럴 줄 알았어요.", "vo/streetwar/tunnel/male01/c17_06_post_det04.wav")
Schema.voices.Add("CitizenMale", "ㄲㅈ2", "물러나세요. 저들에게 들키면 안돼요.", "vo/trainyard/male01/cit_bench01.wav")
Schema.voices.Add("CitizenMale", "ㄷㅊ4", "밖에서 이야기하는 모습을 보이면 안돼요.", "vo/trainyard/male01/cit_bench02.wav")
Schema.voices.Add("CitizenMale", "앉지마", "옆에 앉지 마세요. 의심한다고요.", "vo/trainyard/male01/cit_bench03.wav")
Schema.voices.Add("CitizenMale", "비둘기", "비둘기가 무서워서 도망가잖아요.", "vo/trainyard/male01/cit_bench04.wav")
Schema.voices.Add("CitizenMale", "줄서", "줄은 끝에서 시작해요.", "vo/trainyard/male01/cit_foodline01.wav")
Schema.voices.Add("CitizenMale", "줄서2", "다른 사람들처럼 줄을 서서 순서를 기다려요.", "vo/trainyard/male01/cit_foodline02.wav")
Schema.voices.Add("CitizenMale", "배급식", "이걸 먹으려고 줄을 서다니 진짜 배가 고픈 모양이군.", "vo/trainyard/male01/cit_foodline03.wav")
Schema.voices.Add("CitizenMale", "기동대지원", "따뜻한 밥만 준다면 바로 시민 보호 기동대에 지원할 거예요. 정말이예요.", "vo/trainyard/male01/cit_foodline04.wav")
Schema.voices.Add("CitizenMale", "그만", "그만해요.", "vo/trainyard/male01/cit_hit01.wav")
Schema.voices.Add("CitizenMale", "그만3", "그만하라니까요.", "vo/trainyard/male01/cit_hit02.wav")
Schema.voices.Add("CitizenMale", "조심3", "조심 좀 하세요.", "vo/trainyard/male01/cit_hit03.wav")
Schema.voices.Add("CitizenMale", "그만2", "이제 그만해요.", "vo/trainyard/male01/cit_hit05.wav")
Schema.voices.Add("CitizenMale", "여긴처음", "여긴 처음이죠?", "vo/trainyard/male01/cit_pedestrian01.wav")
Schema.voices.Add("CitizenMale", "ㄷㅊ2", "충고 하나 해드릴게요. 아무 말도 마세요.", "vo/trainyard/male01/cit_pedestrian02.wav")
Schema.voices.Add("CitizenMale", "ㄷㅊ5", "밖에서 이야기를 나누면 우리 둘 다 위험해져요.", "vo/trainyard/male01/cit_pedestrian03.wav")
Schema.voices.Add("CitizenMale", "ㄷㅊ3", "이야기하는 모습을 들키면 안돼요.", "vo/trainyard/male01/cit_pedestrian04.wav")
Schema.voices.Add("CitizenMale", "못도와줌", "도와주고 싶지만 제가 할 수 있는 게 아니에요.", "vo/trainyard/male01/cit_pedestrian05.wav")
Schema.voices.Add("CitizenMale", "세번째", "이게 벌써 올해 세번째야.", "vo/trainyard/male01/cit_term_ques02.wav")
Schema.voices.Add("CitizenMale", "ㅁㅊ2", "오, 안돼. 결국 그렇게 하는군.", "vo/trainyard/male01/cit_tvbust05.wav")
Schema.voices.Add("CitizenMale", "상황별로2", "별로 좋아보이지 않아.", "vo/trainyard/male01/cit_window_use01.wav")
Schema.voices.Add("CitizenMale", "오는중", "확실히 이곳으로 오고 있어.", "vo/trainyard/male01/cit_window_use02.wav")
Schema.voices.Add("CitizenMale", "터질일", "언젠간 터질 일이였어.", "vo/trainyard/male01/cit_window_use03.wav")
Schema.voices.Add("CitizenMale", "다옴", "온 동네에서 다 나타났군.", "vo/trainyard/male01/cit_window_use04.wav")

Schema.voices.Add("CitizenFemale", "실탄", "여기 실탄이요.", "vo/npc/female01/ammo03.wav")
Schema.voices.Add("CitizenFemale", "실탄2", "실탄을 챙기세요.", "vo/npc/female01/ammo04.wav")
Schema.voices.Add("CitizenFemale", "또시작", "또 시작이네.", "vo/npc/female01/answer01.wav")
Schema.voices.Add("CitizenFemale", "안말려", "말리지 않을게요.", "vo/npc/female01/answer02.wav")
Schema.voices.Add("CitizenFemale", "나도", "나도.", "vo/npc/female01/answer03.wav")
Schema.voices.Add("CitizenFemale", "생각마", "자꾸 생각하지 말아요.", "vo/npc/female01/answer04.wav")
Schema.voices.Add("CitizenFemale", "나중에", "그런 이야기는 나중에 하죠.", "vo/npc/female01/answer05.wav")
Schema.voices.Add("CitizenFemale", "공감", "맞아요.", "vo/npc/female01/answer07.wav")
Schema.voices.Add("CitizenFemale", "알아", "무슨 말인지 알아요.", "vo/npc/female01/answer08.wav")
Schema.voices.Add("CitizenFemale", "혼잣말", "또 혼잣말을 하는군요?", "vo/npc/female01/answer09.wav")
Schema.voices.Add("CitizenFemale", "목소리 커", "목소리가 너무 커요.", "vo/npc/female01/answer10.wav")
Schema.voices.Add("CitizenFemale", "왜 몰라", "그걸 모르는 사람이 어디있어요?", "vo/npc/female01/answer11.wav")
Schema.voices.Add("CitizenFemale", "자꾸생각", "자꾸 그런 생각이 들어요.", "vo/npc/female01/answer12.wav")
Schema.voices.Add("CitizenFemale", "ㅇㅇ2", "듣고 있어요.", "vo/npc/female01/answer13.wav")
Schema.voices.Add("CitizenFemale", "마찬가지", "하, 나도 마찬가지예요.", "vo/npc/female01/answer14.wav")
Schema.voices.Add("CitizenFemale", "그럴수도", "한편으론 그럴수도 있죠.", "vo/npc/female01/answer15.wav")
Schema.voices.Add("CitizenFemale", "처음부터?", "처음부터 정말 그렇게 생각했어요?", "vo/npc/female01/answer16.wav")
Schema.voices.Add("CitizenFemale", "ㄷㅊ", "꼭 입 다물라고 말해야 알겠어요?", "vo/npc/female01/answer17.wav")
Schema.voices.Add("CitizenFemale", "집중3", "코 앞에 닥친 일에나 신경써요.", "vo/npc/female01/answer18.wav")
Schema.voices.Add("CitizenFemale", "집중", "일에 좀 집중하세요.", "vo/npc/female01/answer19.wav")
Schema.voices.Add("CitizenFemale", "집중2", "칫, 마음이 다른 데 있군요?", "vo/npc/female01/answer20.wav")
Schema.voices.Add("CitizenFemale", "믿지마", "너무 믿지 마세요", "vo/npc/female01/answer21.wav")
Schema.voices.Add("CitizenFemale", "넌몰라", "당신은 몰라요.", "vo/npc/female01/answer22.wav")
Schema.voices.Add("CitizenFemale", "ㅁㄹ", "모르겠는데요?", "vo/npc/female01/answer23.wav")
Schema.voices.Add("CitizenFemale", "나?2", "왜 나한태 말하죠?", "vo/npc/female01/answer24.wav")
Schema.voices.Add("CitizenFemale", "어때서", "그게 어때서요.", "vo/npc/female01/answer25.wav")
Schema.voices.Add("CitizenFemale", "똑똑하군", "알려줘서 정말 고맙네요.", "vo/npc/female01/answer26.wav")
Schema.voices.Add("CitizenFemale", "정말?", "정말이예요?", "vo/npc/female01/answer27.wav")
Schema.voices.Add("CitizenFemale", "돈", "그렇게 말할 때마다 돈이 생겼으면 좋으련만.", "vo/npc/female01/answer28.wav")
Schema.voices.Add("CitizenFemale", "뭘원해", "제가 어떻게 했으면 좋겠어요?", "vo/npc/female01/answer29.wav")
Schema.voices.Add("CitizenFemale", "나?", "나 말이예요?", "vo/npc/female01/answer30.wav")
Schema.voices.Add("CitizenFemale", "방지", "그런 말은 애초에 꺼내지 않는 게 좋아요.", "vo/npc/female01/answer31.wav")
Schema.voices.Add("CitizenFemale", "ㅇㅇ", "맞아.", "vo/npc/female01/answer32.wav")
Schema.voices.Add("CitizenFemale", "동감", "전적으로 동감이예요.", "vo/npc/female01/answer33.wav")
Schema.voices.Add("CitizenFemale", "하와이", "하와이를 기억해요.", "vo/npc/female01/answer34.wav")
Schema.voices.Add("CitizenFemale", "여유찾아2", "뭔가를 가져본 때가 언제였는지... 기억도 안나요.", "vo/npc/female01/answer35.wav")
Schema.voices.Add("CitizenFemale", "여유찾아", "마음의 여유를 찾으세요.", "vo/npc/female01/answer36.wav")
Schema.voices.Add("CitizenFemale", "처음아님", "처음도 아니잖아요?", "vo/npc/female01/answer37.wav")
Schema.voices.Add("CitizenFemale", "ㄹㅇ?", "정말 확실해요?", "vo/npc/female01/answer38.wav")
Schema.voices.Add("CitizenFemale", "상관마", "상관 말아요.", "vo/npc/female01/answer39.wav")
Schema.voices.Add("CitizenFemale", "충분해", "그래요. 그걸로 충분해요.", "vo/npc/female01/answer40.wav")
Schema.voices.Add("CitizenFemale", "뒤에있어", "뒤에 있어요!", "vo/npc/female01/behindyou01.wav")
Schema.voices.Add("CitizenFemale", "바빠", "바쁜 거 안보이세요?", "vo/npc/female01/busy02.wav")
Schema.voices.Add("CitizenFemale", "받아", "이봐 거기! 받아요!", "vo/npc/female01/cit_dropper01.wav")
Schema.voices.Add("CitizenFemale", "아래조심", "아래 조심해요!", "vo/npc/female01/cit_dropper04.wav")
Schema.voices.Add("CitizenFemale", "기동대2", "보호 기동대다!", "vo/npc/female01/civilprotection01.wav")
Schema.voices.Add("CitizenFemale", "콤바인", "콤바인!", "vo/npc/female01/combine01.wav")
Schema.voices.Add("CitizenFemale", "장전엄호", "장전할 때 날 엄호해요.", "vo/npc/female01/coverwhilereload01.wav")
Schema.voices.Add("CitizenFemale", "기동대", "기동대!", "vo/npc/female01/cps01.wav")
Schema.voices.Add("CitizenFemale", "뭔가 할", "뭐라도 해야하지 않을까요?", "vo/npc/female01/doingsomething.wav")
Schema.voices.Add("CitizenFemale", "실례", "실례해요.", "vo/npc/female01/excuseme01.wav")
Schema.voices.Add("CitizenFemale", "훌륭해요", "훌륭해요.", "vo/npc/female01/fantastic01.wav")
Schema.voices.Add("CitizenFemale", "굿", "좋아요.", "vo/npc/female01/nice01.wav")
Schema.voices.Add("CitizenFemale", "해냈군요", "해냈군요.", "vo/coast/barn/female01/youmadeit.wav")
Schema.voices.Add("CitizenFemale", "엎드려", "숙여요!", "vo/npc/female01/getdown02.wav")
Schema.voices.Add("CitizenFemale", "언제출발", "언제 출발할 건가요?", "vo/npc/female01/getgoingsoon.wav")
Schema.voices.Add("CitizenFemale", "나가", "당장 여기서 나가요!", "vo/npc/female01/gethellout.wav")
Schema.voices.Add("CitizenFemale", "맙소사", "맙소사.", "vo/npc/female01/goodgod.wav")
Schema.voices.Add("CitizenFemale", "어쩌죠", "이제 어쩌죠?", "vo/npc/female01/gordead_ans01.wav")
Schema.voices.Add("CitizenFemale", "안풀림", "왜 이리 잘 풀리나 했어요.", "vo/npc/female01/gordead_ans02.wav")
Schema.voices.Add("CitizenFemale", "ㅇㅇ3", "그러게요.", "vo/npc/female01/gordead_ans03.wav")
Schema.voices.Add("CitizenFemale", "세상에", "오, 세상에.", "vo/npc/female01/gordead_ans04.wav")
Schema.voices.Add("CitizenFemale", "ㄴㄴ2", "아, 안돼.", "vo/npc/female01/gordead_ans05.wav")
Schema.voices.Add("CitizenFemale", "ㄴㄴ4", "제발, 안돼.", "vo/npc/female01/gordead_ans06.wav")
Schema.voices.Add("CitizenFemale", "농담하지마", "지금 농담같은 걸 하면 가만두지 않겠어요.", "vo/npc/female01/gordead_ans07.wav")
Schema.voices.Add("CitizenFemale", "묻을까", "여기에 묻을까요?", "vo/npc/female01/gordead_ans08.wav")
Schema.voices.Add("CitizenFemale", "모두알려줘", "모두에게 알려주세요.", "vo/npc/female01/gordead_ans10.wav")
Schema.voices.Add("CitizenFemale", "소용없어", "무슨 소용이예요?", "vo/npc/female01/gordead_ans11.wav")
Schema.voices.Add("CitizenFemale", "쓸데없어", "쓸데없는 짓이예요.", "vo/npc/female01/gordead_ans12.wav")
Schema.voices.Add("CitizenFemale", "희망없어", "희망이 없어요.", "vo/npc/female01/gordead_ans13.wav")
Schema.voices.Add("CitizenFemale", "우린끝났어", "우린 끝났어요.", "vo/npc/female01/gordead_ans14.wav")
Schema.voices.Add("CitizenFemale", "어쩌지2", "자, 이제 어쩌죠?", "vo/npc/female01/gordead_ans15.wav")
Schema.voices.Add("CitizenFemale", "처음아님2", "처음이 아니잖아요, 괜찮을 거예요.", "vo/npc/female01/gordead_ans18.wav")
Schema.voices.Add("CitizenFemale", "토나와", "토할 것 같아.", "vo/npc/female01/gordead_ans19.wav")
Schema.voices.Add("CitizenFemale", "크로우바", "누가 크로우바를 가져가세요.", "vo/npc/female01/gordead_ans20.wav")
Schema.voices.Add("CitizenFemale", "죽었어", "죽었어요.", "vo/npc/female01/gordead_ques01.wav")
Schema.voices.Add("CitizenFemale", "끔찍", "끔찍하네요.", "vo/npc/female01/gordead_ques02.wav")
Schema.voices.Add("CitizenFemale", "그럴리가", "그럴리 없어요.", "vo/npc/female01/gordead_ques06.wav")
Schema.voices.Add("CitizenFemale", "죽었어2", "봐요, 죽었어요.", "vo/npc/female01/gordead_ques07.wav")
Schema.voices.Add("CitizenFemale", "큰일", "큰일이예요.", "vo/npc/female01/gordead_ques10.wav")
Schema.voices.Add("CitizenFemale", "천하무적", "천하무적인줄 알았어요.", "vo/npc/female01/gordead_ques11.wav")
Schema.voices.Add("CitizenFemale", "희망없어2", "이게 마지막 희망이였어요?", "vo/npc/female01/gordead_ques13.wav")
Schema.voices.Add("CitizenFemale", "끝날수없어", "이렇게 끝날 순 없어요.", "vo/npc/female01/gordead_ques14.wav")
Schema.voices.Add("CitizenFemale", "남길말", "남기고 싶은 말이라도?", "vo/npc/female01/gordead_ques17.wav")
Schema.voices.Add("CitizenFemale", "잡았다", "잡았다!", "vo/npc/female01/gotone01.wav")
Schema.voices.Add("CitizenFemale", "장전", "장전할게요!", "vo/npc/female01/gottareload01.wav")
Schema.voices.Add("CitizenFemale", "헬기", "무장헬기!", "vo/npc/female01/gunship02.wav")
Schema.voices.Add("CitizenFemale", "맨핵", "맨핵!", "vo/npc/female01/hacks01.wav")
Schema.voices.Add("CitizenFemale", "헤드크랩", "헤드크랩!", "vo/npc/female01/headcrabs01.wav")
Schema.voices.Add("CitizenFemale", "이쪽3", "이쪽이다!", "vo/npc/female01/headsup01.wav")
Schema.voices.Add("CitizenFemale", "메드킷", "메드 키트를 받아요.", "vo/npc/female01/health01.wav")
Schema.voices.Add("CitizenFemale", "메드킷2", "여기요, 메드 키트를 받아요.", "vo/npc/female01/health02.wav")
Schema.voices.Add("CitizenFemale", "메드킷3", "여기요, 메드 키트요.", "vo/npc/female01/health04.wav")
Schema.voices.Add("CitizenFemale", "보충해", "여기요, 보충 좀 해요", "vo/npc/female01/health05.wav")
Schema.voices.Add("CitizenFemale", "도와줘", "도와줘요!", "vo/npc/female01/help01.wav")
Schema.voices.Add("CitizenFemale", "맨핵3", "맨핵이 온다!", "vo/npc/female01/hearcomehacks01.wav")
Schema.voices.Add("CitizenFemale", "그들온다", "그들이 와요!", "vo/npc/female01/heretheycome01.wav")
Schema.voices.Add("CitizenFemale", "도우러온줄", "우릴 도우러 온 줄 알았어요.", "vo/npc/female01/heretohelp01.wav")
Schema.voices.Add("CitizenFemale", "도우러온줄2", "우릴 도우러 온 줄 알았다고요.", "vo/npc/female01/heretohelp02.wav")
Schema.voices.Add("CitizenFemale", "배맞음", "으허억, 배를 맞았어.", "vo/npc/female01/hitingut01.wav")
Schema.voices.Add("CitizenFemale", "자리사수", "남아서 자리를 사수하겠습니다.", "vo/npc/female01/holddownspot01.wav")
Schema.voices.Add("CitizenFemale", "여기남음", "여기 남을게요.", "vo/npc/female01/illstayhere01.wav")
Schema.voices.Add("CitizenFemale", "다침", "다쳤어요!", "vo/npc/female01/imhurt01.wav")
Schema.voices.Add("CitizenFemale", "여기남음2", "여기 남겠어요.", "vo/npc/female01/imstickinghere01.wav")
Schema.voices.Add("CitizenFemale", "온다", "온다!", "vo/npc/female01/incoming02.wav")
Schema.voices.Add("CitizenFemale", "맨핵2", "맨핵이다!", "vo/npc/female01/itsamanhack01.wav")
Schema.voices.Add("CitizenFemale", "안내해요2", "어서 안내해요.", "vo/npc/female01/leadtheway01.wav")
Schema.voices.Add("CitizenFemale", "안내해요", "안내해요!", "vo/npc/female01/leadtheway02.wav")
Schema.voices.Add("CitizenFemale", "ㄱㄱ", "가요.", "vo/npc/female01/letsgo01.wav")
Schema.voices.Add("CitizenFemale", "맛어때", "이봐, 맛이 어때!", "vo/npc/female01/likethat.wav")
Schema.voices.Add("CitizenFemale", "내구역", "여긴 내 구역이고, 끝까지 지킬 거예요.", "vo/npc/female01/littlecorner01.wav")
Schema.voices.Add("CitizenFemale", "내팔", "으헉, 내 팔.", "vo/npc/female01/myarm01.wav")
Schema.voices.Add("CitizenFemale", "배맞음2", "으허헉, 배가!", "vo/npc/female01/mygut02.wav")
Schema.voices.Add("CitizenFemale", "내다리", "으헉, 내 다리.", "vo/npc/female01/myleg01.wav")
Schema.voices.Add("CitizenFemale", "ㄴㄴ", "안돼!", "vo/npc/female01/no01.wav")
Schema.voices.Add("CitizenFemale", "ㄴㄴ5", "안돼, 안돼!", "vo/npc/female01/no01.wav")
Schema.voices.Add("CitizenFemale", "당신아냐", "당신을 믿는 게 아니였어요.", "vo/npc/female01/notthemanithought01.wav")
Schema.voices.Add("CitizenFemale", "ㄴㄴ3", "오, 안돼.", "vo/npc/female01/ohno.wav")
Schema.voices.Add("CitizenFemale", "네", "네.", "vo/npc/female01/ok01.wav")
Schema.voices.Add("CitizenFemale", "준비완료", "네, 준비됬어요.", "vo/npc/female01/okimready01.wav")
Schema.voices.Add("CitizenFemale", "내꺼", "내 꺼, 그리고 또 내 꺼.", "vo/npc/female01/oneforme.wav")
Schema.voices.Add("CitizenFemale", "ㅂㅋ", "좀 지나갈게요.", "vo/npc/female01/outofyourway02.wav")
Schema.voices.Add("CitizenFemale", "이쪽", "이쪽이요.", "vo/npc/female01/overhere01.wav")
Schema.voices.Add("CitizenFemale", "저쪽", "저쪽이요.", "vo/npc/female01/overthere01.wav")
Schema.voices.Add("CitizenFemale", "전쟁안끝나", "전쟁이 끝날 것 같지가 않아요.", "vo/npc/female01/question01.wav")
Schema.voices.Add("CitizenFemale", "보험팔래", "마음 편히 보험이나 팔러 다니면 얼마나 좋을까.", "vo/npc/female01/question02.wav")
Schema.voices.Add("CitizenFemale", "기대없음", "더이상 기대도 없어요.", "vo/npc/female01/question03.wav")
Schema.voices.Add("CitizenFemale", "다끝나면", "모든 게 다 끝나면 난... 아, 쓸데없는 소리.", "vo/npc/female01/question04.wav")
Schema.voices.Add("CitizenFemale", "데자부", "데자부같아요.", "vo/npc/female01/question05.wav")
Schema.voices.Add("CitizenFemale", "치즈먹는상상", "때론 치즈를 먹는 상상을 해요.", "vo/npc/female01/question06.wav")
Schema.voices.Add("CitizenFemale", "자유의냄새", "느껴져? 자유의 냄새예요.", "vo/npc/female01/question07.wav")
Schema.voices.Add("CitizenFemale", "브린박사", "브린 박사, 내 손에 잡히기만 해봐.", "vo/npc/female01/question08.wav")
Schema.voices.Add("CitizenFemale", "배고파2", "뭐든 닥치는대로 먹고 싶어요.", "vo/npc/female01/question09.wav")
Schema.voices.Add("CitizenFemale", "이날", "이 날이 결국 왔다니 믿기지가 않아요.", "vo/npc/female01/question10.wav")
Schema.voices.Add("CitizenFemale", "변수", "이건 계획에 없었던 게 분명해요.", "vo/npc/female01/question11.wav")
Schema.voices.Add("CitizenFemale", "설상가상", "상황이 좋아지기는 커녕 더 나빠지는 것 같아요.", "vo/npc/female01/question12.wav")
Schema.voices.Add("CitizenFemale", "내인생", "내 인생을 다시 살 수만 있다면.", "vo/npc/female01/question13.wav")
Schema.voices.Add("CitizenFemale", "안말해", "지금 무슨 생각이 났는데, 말하지 않을래요.", "vo/npc/female01/question14.wav")
Schema.voices.Add("CitizenFemale", "ㄲㅈ", "날 집요하게 쫒아다니지는 않겠죠.", "vo/npc/female01/question15.wav")
Schema.voices.Add("CitizenFemale", "기회다", "결국 기회는 왔어요.", "vo/npc/female01/question16.wav")
Schema.voices.Add("CitizenFemale", "느껴져", "느껴져요? 난 느껴져요.", "vo/npc/female01/question17.wav")
Schema.voices.Add("CitizenFemale", "못느껴", "더이상 느낄 수가 없어요.", "vo/npc/female01/question18.wav")
Schema.voices.Add("CitizenFemale", "샤워", "마지막으로 샤워한 게 언제인지 기억조차 안나요.", "vo/npc/female01/question19.wav")
Schema.voices.Add("CitizenFemale", "끔찍한기억", "훗날... 끔찍한 기억으로만 남게 되겠죠.", "vo/npc/female01/question20.wav")
Schema.voices.Add("CitizenFemale", "홀수", "꼭 그렇다는 건 아니지만 왠지 홀수는 별로인데요.", "vo/npc/female01/question21.wav")
Schema.voices.Add("CitizenFemale", "무시ㄴ", "내 생각은 다들 무시하는거예요?", "vo/npc/female01/question22.wav")
Schema.voices.Add("CitizenFemale", "휘파람", "이 음이 머리에서 떠나질 않아요. *(휘파람)*", "vo/npc/female01/question23.wav")
Schema.voices.Add("CitizenFemale", "매일똑같아", "매일매일이 똑같다는 것만 알 뿐이죠.", "vo/npc/female01/question25.wav")
Schema.voices.Add("CitizenFemale", "ㅁㅊ", "말도 안돼.", "vo/npc/female01/question26.wav")
Schema.voices.Add("CitizenFemale", "토나와2", "먹은 게 잘못된 것 같아요.", "vo/npc/female01/question27.wav")
Schema.voices.Add("CitizenFemale", "배고파", "배가 고프군요.", "vo/npc/female01/question28.wav")
Schema.voices.Add("CitizenFemale", "연애", "모두 다 끝나면 연애를 할거예요.", "vo/npc/female01/question29.wav")
Schema.voices.Add("CitizenFemale", "아이들", "아이들이 이 모습을 보지 못해서 다행이예요.", "vo/npc/female01/question30.wav")
Schema.voices.Add("CitizenFemale", "ㄹㄷ", "준비됬습니다!", "vo/npc/female01/readywhenyouare01.wav")
Schema.voices.Add("CitizenFemale", "ㅌㅌ", "도망쳐요!", "vo/npc/female01/runforyourlife01.wav")
Schema.voices.Add("CitizenFemale", "스캐너", "스캐너!", "vo/npc/female01/scanners01.wav")
Schema.voices.Add("CitizenFemale", "ㅈㅅ", "죄송해요.", "vo/npc/female01/sorry01.wav")
Schema.voices.Add("CitizenFemale", "ㅇㅋ", "알겠습니다.", "vo/npc/female01/squad_affirm01.wav")
Schema.voices.Add("CitizenFemale", "뭐든지", "뭐든지요.", "vo/npc/female01/squad_affirm03.wav")
Schema.voices.Add("CitizenFemale", "ㅇㅋㄱ", "좋아요, 갑니다.", "vo/npc/female01/squad_affirm04.wav")
Schema.voices.Add("CitizenFemale", "저도요", "저도요.", "vo/npc/female01/squad_affirm05.wav")
Schema.voices.Add("CitizenFemale", "본전", "믿져야 본전이죠.", "vo/npc/female01/squad_affirm06.wav")
Schema.voices.Add("CitizenFemale", "드디어", "드디어 오는군요.", "vo/npc/female01/squad_approach02.wav")
Schema.voices.Add("CitizenFemale", "우리쪽", "우리 쪽으로.", "vo/npc/female01/squad_approach03.wav")
Schema.voices.Add("CitizenFemale", "이쪽2", "이쪽이야.", "vo/npc/female01/squad_away01.wav")
Schema.voices.Add("CitizenFemale", "여기로", "여기로.", "vo/npc/female01/squad_away02.wav")
Schema.voices.Add("CitizenFemale", "어서2", "자, 어서요.", "vo/npc/female01/squad_follow02.wav")
Schema.voices.Add("CitizenFemale", "ㄱㄷ", "기다려요.", "vo/npc/female01/squad_reinforce_group04.wav")
Schema.voices.Add("CitizenFemale", "ㄱㄷ2", "기다려주세요.", "vo/npc/female01/squad_reinforce_single04.wav")
Schema.voices.Add("CitizenFemale", "스트라이더", "스트라이더!", "vo/npc/female01/strider.wav")
Schema.voices.Add("CitizenFemale", "엄호", "엄호해요!", "vo/npc/female01/takecover02.wav")
Schema.voices.Add("CitizenFemale", "괜찮은데", "이거 괜찮은데?", "vo/npc/female01/thislldonicely01.wav")
Schema.voices.Add("CitizenFemale", "저기", "저기!", "vo/npc/female01/upthere01.wav")
Schema.voices.Add("CitizenFemale", "허튼소리", "허튼 소리하지 마요.", "vo/npc/female01/vanswer01.wav")
Schema.voices.Add("CitizenFemale", "보르티ㅅㅂ", "젠장할, 보르티.", "vo/npc/female01/vanswer02.wav")
Schema.voices.Add("CitizenFemale", "어떻게하지", "어떻게 처리해야 할 지 모르겠어요.", "vo/npc/female01/vanswer03.wav")
Schema.voices.Add("CitizenFemale", "내가처리할까", "제가 처리할까요?", "vo/npc/female01/vanswer04.wav")
Schema.voices.Add("CitizenFemale", "뭐래", "알아듣게 말해요.", "vo/npc/female01/vanswer05.wav")
Schema.voices.Add("CitizenFemale", "나한테서", "나한테서 들었잖아요.", "vo/npc/female01/vanswer06.wav")
Schema.voices.Add("CitizenFemale", "참아", "그러니까 우리가 참는거죠.", "vo/npc/female01/vanswer07.wav")
Schema.voices.Add("CitizenFemale", "참아2", "혼자라면 더 잘 참았을거예요.", "vo/npc/female01/vanswer08.wav")
Schema.voices.Add("CitizenFemale", "말되네", "그거 말 되네요.", "vo/npc/female01/vanswer09.wav")
Schema.voices.Add("CitizenFemale", "이해안됨", "나에게 문제가 있는 것 같아. 거의 알아들은 것 같았는데.", "vo/npc/female01/vanswer10.wav")
Schema.voices.Add("CitizenFemale", "보르티익숙함", "보르티에게 좀 익숙해졌어요.", "vo/npc/female01/vanswer11.wav")
Schema.voices.Add("CitizenFemale", "보르티철학", "보르티 철학은 없어요.", "vo/npc/female01/vanswer12.wav")
Schema.voices.Add("CitizenFemale", "그만5", "그만해요. 못참겠군요.", "vo/npc/female01/vanswer13.wav")
Schema.voices.Add("CitizenFemale", "헛수고", "내가 뭘 바라고 이 일을 했죠?", "vo/npc/female01/vanswer14.wav")
Schema.voices.Add("CitizenFemale", "보지마", "그렇게 쳐다보지 말아요.", "vo/npc/female01/vquestion01.wav")
Schema.voices.Add("CitizenFemale", "적응안됨", "절대 익숙해질 수 없는 것도 있죠.", "vo/npc/female01/vquestion02.wav")
Schema.voices.Add("CitizenFemale", "살아남음", "지금까지 어떻게 살아남을 수 있었는지 모르겠어요.", "vo/npc/female01/vquestion03.wav")
Schema.voices.Add("CitizenFemale", "당신누구", "당신과 어떻게 같이 있게 됬는지 모르겠군요.", "vo/npc/female01/vquestion04.wav")
Schema.voices.Add("CitizenFemale", "보르티ㄱㅊ", "괜찮아요, 보르티.", "vo/npc/female01/vquestion05.wav")
Schema.voices.Add("CitizenFemale", "보르티충분함", "보르티면 충분해요.", "vo/npc/female01/vquestion06.wav")
Schema.voices.Add("CitizenFemale", "보르티친구", "누군가가 나에게 말해줬다면 보르티와 친구가 되었을텐데.", "vo/npc/female01/vquestion07.wav")
Schema.voices.Add("CitizenFemale", "ㄱㄷ?", "누구 기다려요?", "vo/npc/female01/waitingsomebody.wav")
Schema.voices.Add("CitizenFemale", "조심", "조심해요!", "vo/npc/female01/watchout.wav")
Schema.voices.Add("CitizenFemale", "조심2", "조심하라구요!", "vo/npc/female01/watchwhat.wav")
Schema.voices.Add("CitizenFemale", "믿었음", "우린 믿었다구요!", "vo/npc/female01/wetrustedyou01.wav")
Schema.voices.Add("CitizenFemale", "이런", "이런.", "vo/npc/female01/whoops01.wav")
Schema.voices.Add("CitizenFemale", "장전해", "장전하세요.", "vo/npc/female01/youdbetterreload01.wav")
Schema.voices.Add("CitizenFemale", "ㅇㅇ4", "바로 그거예요.", "vo/npc/female01/yougotit02.wav")
Schema.voices.Add("CitizenFemale", "좀비", "좀비다!", "vo/npc/female01/zombies01.wav")
Schema.voices.Add("CitizenFemale", "철수중4", "어서 가세요. 이제 떠나야 되요.", "vo/canals/female01/gunboat_breakcamp.wav")
Schema.voices.Add("CitizenFemale", "끝장내", "그들을 끝장내주세요.", "vo/canals/female01/gunboat_giveemhell.wav")
Schema.voices.Add("CitizenFemale", "철수중3", "어서 서둘러야 해요. 이 캠프를 부순 다음, 여기서 빠져나가야 합니다.", "vo/canals/female01/gunboat_hurry.wav")
Schema.voices.Add("CitizenFemale", "철수중2", "정말 잘 오셨습니다. 들키기 전에 어서 여길 빠져나가야 해요.", "vo/canals/female01/gunboat_justintime.wav")
Schema.voices.Add("CitizenFemale", "어서3", "어서 가요! 우리를 노리기 전에 여기를 떠나야 해요!", "vo/canals/female01/gunboat_moveone.wav")
Schema.voices.Add("CitizenFemale", "보트", "보트는 여기 두시면 되요. 안전합니다.", "vo/canals/female01/gunboat_parkboat.wav")
Schema.voices.Add("CitizenFemale", "철수중", "딱 맞춰 오셨어요. 콤바인이 쳐들어 오기 전에 여길 떠나야 해서, 지금 막 철수하려던 중이였습니다.", "vo/canals/female01/gunboat_pullout.wav")
Schema.voices.Add("CitizenFemale", "어서", "어서요!", "vo/canals/female01/stn6_go_nag02.wav")
Schema.voices.Add("CitizenFemale", "포탄공격", "포탄 공격이다!", "vo/canals/female01/stn6_shellingus.wav")
Schema.voices.Add("CitizenFemale", "드롭십2", "오, 이런. 드롭십이 와요!", "vo/coast/barn/female01/crapships.wav")
Schema.voices.Add("CitizenFemale", "차버려", "차를 버려야 합니다. 그들이 지금 차를 찾고 있어요.", "vo/coast/barn/female01/ditchcar.wav")
Schema.voices.Add("CitizenFemale", "드롭십등대", "저기 등대에 드롭십이 있다!", "vo/coast/barn/female01/drop_lite.wav")
Schema.voices.Add("CitizenFemale", "드롭십3", "드롭십, 저쪽에서 와요!", "vo/coast/barn/female01/drop_road.wav")
Schema.voices.Add("CitizenFemale", "저쪽ㄱ", "저쪽으로 쭉 가세요. 조심하시고요.", "vo/coast/barn/female01/exit_watchstep.wav")
Schema.voices.Add("CitizenFemale", "차넣어2", "어서요! 차를 헛간에 넣어요!", "vo/coast/barn/female01/getcarinbarn.wav")
Schema.voices.Add("CitizenFemale", "차넣어", "차를 차고에 넣어요.", "vo/coast/barn/female01/getcaringarage.wav")
Schema.voices.Add("CitizenFemale", "벗어나", "길에서 벗어나요!", "vo/coast/barn/female01/getoffroad01.wav")
Schema.voices.Add("CitizenFemale", "걸어가", "저희가 차에서 무기를 가져올게요. 지금부터는 걸어서 가셔야 합니다.", "vo/coast/barn/female01/gettauoff.wav")
Schema.voices.Add("CitizenFemale", "드롭십", "드롭십이다!", "vo/coast/barn/female01/incomingdropship.wav")
Schema.voices.Add("CitizenFemale", "헬기2", "무장 헬기다!", "vo/coast/barn/female01/lite_gunship01.wav")
Schema.voices.Add("CitizenFemale", "넣어", "거기에 넣어요!", "vo/coast/barn/female01/parkit.wav")
Schema.voices.Add("CitizenFemale", "페로포드", "페로포드의 효능은 제가 장담합니다.", "vo/coast/bugbait/female01/pheropod_nag02.wav")
Schema.voices.Add("CitizenFemale", "개미귀신끝", "개미귀신들이 더는 괴롭히지 않을 겁니다.", "vo/coast/bugbait/female01/pheropod_nag03.wav")
Schema.voices.Add("CitizenFemale", "헤이", "헤이!", "vo/coast/odessa/female01/nlo_cheer01.wav")
Schema.voices.Add("CitizenFemale", "굿2", "우후우!", "vo/coast/odessa/female01/nlo_cheer02.wav")
Schema.voices.Add("CitizenFemale", "굿3", "우후! 하하하!", "vo/coast/odessa/female01/nlo_cheer03.wav")
Schema.voices.Add("CitizenFemale", "게이트2", "여기로 차를 가져오세요. 게이트를 열겠습니다.", "vo/coast/odessa/female01/nlo_citizen_bringcar.wav")
Schema.voices.Add("CitizenFemale", "운전조심", "조심해서 모세요.", "vo/coast/odessa/female01/nlo_citizen_drivesafe.wav")
Schema.voices.Add("CitizenFemale", "지하실", "어서 지하실로 가셔야 합니다. 언제 공격이 시작될 지 몰라요.", "vo/coast/odessa/female01/nlo_citizen_greet01.wav")
Schema.voices.Add("CitizenFemale", "시간없음", "여기서 꾸물거릴 시간이 없어요. 콤바인이 접근해 오고 있다구요.", "vo/coast/odessa/female01/nlo_citizen_greet03.wav")
Schema.voices.Add("CitizenFemale", "지하실2", "어서 지하실로 가세요! 지금 저들이 공격해오면 모든 사람들이 위험에 빠진다구요!", "vo/coast/odessa/female01/nlo_citizen_greet04.wav")
Schema.voices.Add("CitizenFemale", "게이트3", "차에 타세요. 제가 게이트를 열겠습니다.", "vo/coast/odessa/female01/nlo_getyourjeep.wav")
Schema.voices.Add("CitizenFemale", "차타", "차에 타세요. 걸어서는 먼 길을 갈 수 없어요.", "vo/coast/odessa/female01/nlo_yourcarsir.wav")
Schema.voices.Add("CitizenFemale", "지뢰", "지뢰 파편을 조심해요! 여기저기 널려있어요!", "vo/streetwar/barricade/female01/c17_05_hoppers.wav")
Schema.voices.Add("CitizenFemale", "ㅂㅋ2", "지나가게 해줘요!", "vo/streetwar/barricade/female01/c17_05_letusthru.wav")
Schema.voices.Add("CitizenFemale", "지뢰2", "지뢰 파편을 버리지 마세요. 그걸 사용해서 콤바인과 싸울 수 있어요.", "vo/streetwar/barricade/female01/c17_05_minehelp1.wav")
Schema.voices.Add("CitizenFemale", "지뢰3", "지뢰 파편을 치워버리지 마세요. 지뢰 파편을 모아두었다가 필요한 곳에 박아서 사용할 수 있어요.", "vo/streetwar/barricade/female01/c17_05_minehelp2.wav")
Schema.voices.Add("CitizenFemale", "게이트", "게이트를 열어요!", "vo/streetwar/barricade/female01/c17_05_opengate.wav")
Schema.voices.Add("CitizenFemale", "꺼내줘", "이봐요! 우릴 좀 꺼내줘요!", "vo/streetwar/nexus/female01/c17_10_letusout.wav")
Schema.voices.Add("CitizenFemale", "기념비", "말 기념비로 가요!", "vo/streetwar/rubble/female01/d3_c17_13_horse01.wav")
Schema.voices.Add("CitizenFemale", "기념비2", "말 기념비로 가야 해요!", "vo/streetwar/rubble/female01/d3_c17_13_horse01.wav")
Schema.voices.Add("CitizenFemale", "스나이퍼", "도와줘요! 이 아래가 더 안전한 줄 알았어요. 여기가 이렇게 위험한 지 생각도 못했어요. 몇 사람들은 스나이퍼들이 있다는 걸 알면서도 위험을 감수하고 올라갔어요. 아마 아직도 위에 있을 거예요.", "vo/streetwar/sniper/female01/c17_09_cellar.wav")
Schema.voices.Add("CitizenFemale", "버텨", "조금만 더 버티세요. 거의 다 됬어요!", "vo/streetwar/tunnel/female01/c17_06_det02.wav")
Schema.voices.Add("CitizenFemale", "하나남음", "좋아, 하나 남았어요.", "vo/streetwar/tunnel/female01/c17_06_det03.wav")
Schema.voices.Add("CitizenFemale", "폭발", "물러서요! 폭발시킵니다!", "vo/streetwar/tunnel/female01/c17_06_det04.wav")
Schema.voices.Add("CitizenFemale", "문열어", "이봐요, 저예요. 문 열어요.", "vo/streetwar/tunnel/female01/c17_06_password01.wav")
Schema.voices.Add("CitizenFemale", "암호2", "암호를 대요.", "vo/streetwar/tunnel/female01/c17_06_password02.wav")
Schema.voices.Add("CitizenFemale", "들어와", "들어와요.", "vo/streetwar/tunnel/female01/c17_06_password04.wav")
Schema.voices.Add("CitizenFemale", "지나가", "자, 어서 지나가요.", "vo/streetwar/tunnel/female01/c17_06_plank01.wav")
Schema.voices.Add("CitizenFemale", "여기남음2", "다른 사람들이 또 지나갈 지도 모르니 전 여기 있어야 해요.", "vo/streetwar/tunnel/female01/c17_06_plank02.wav")
Schema.voices.Add("CitizenFemale", "제때", "여긴 엉망이군요. 그래도 제 때에 오셔서 다행이예요.", "vo/streetwar/tunnel/female01/c17_06_post_det02.wav")
Schema.voices.Add("CitizenFemale", "해냈군요2", "정말 해내셨군요. 해내실 줄 알았어요.", "vo/streetwar/tunnel/female01/c17_06_post_det04.wav")
Schema.voices.Add("CitizenFemale", "ㄲㅈ2", "물러나세요. 저들에게 들키면 안돼요.", "vo/trainyard/female01/cit_bench01.wav")
Schema.voices.Add("CitizenFemale", "ㄷㅊ4", "밖에서 이야기하는 모습을 보이면 안돼요.", "vo/trainyard/female01/cit_bench02.wav")
Schema.voices.Add("CitizenFemale", "앉지마", "옆에 앉지 마세요. 의심한다고요.", "vo/trainyard/female01/cit_bench03.wav")
Schema.voices.Add("CitizenFemale", "비둘기", "비둘기가 무서워서 도망가잖아요.", "vo/trainyard/female01/cit_bench04.wav")
Schema.voices.Add("CitizenFemale", "줄서", "줄은 끝에서 시작해요.", "vo/trainyard/female01/cit_foodline01.wav")
Schema.voices.Add("CitizenFemale", "줄서2", "사람들처럼 줄을 서서 순서를 기다려요.", "vo/trainyard/female01/cit_foodline02.wav")
Schema.voices.Add("CitizenFemale", "배급식", "이걸 먹으려고 줄을 서다니 진짜 배가 고픈 모양이네.", "vo/trainyard/female01/cit_foodline03.wav")
Schema.voices.Add("CitizenFemale", "기동대지원", "따뜻한 밥만 준다면 바로 시민 보호 기동대에 지원할 거예요. 정말이예요.", "vo/trainyard/female01/cit_foodline04.wav")
Schema.voices.Add("CitizenFemale", "그만2", "이봐요, 그만해요.", "vo/trainyard/female01/cit_hit01.wav")
Schema.voices.Add("CitizenFemale", "그만", "그만해요.", "vo/trainyard/female01/cit_hit04.wav")
Schema.voices.Add("CitizenFemale", "그만4", "그만하라니까요.", "vo/trainyard/female01/cit_hit02.wav")
Schema.voices.Add("CitizenFemale", "조심3", "조심 좀 하세요.", "vo/trainyard/female01/cit_hit03.wav")
Schema.voices.Add("CitizenFemale", "그만3", "이제 그만해요.", "vo/trainyard/female01/cit_hit05.wav")
Schema.voices.Add("CitizenFemale", "여긴처음", "여긴 처음이죠?", "vo/trainyard/female01/cit_pedestrian01.wav")
Schema.voices.Add("CitizenFemale", "ㄷㅊ2", "충고 하나 해드릴게요. 아무 말도 마세요.", "vo/trainyard/female01/cit_pedestrian02.wav")
Schema.voices.Add("CitizenFemale", "ㄷㅊ5", "밖에서 이야기를 나누면 우리 둘 다 위험해져요.", "vo/trainyard/female01/cit_pedestrian03.wav")
Schema.voices.Add("CitizenFemale", "ㄷㅊ3", "이야기하는 모습을 들키면 안돼요.", "vo/trainyard/female01/cit_pedestrian04.wav")
Schema.voices.Add("CitizenFemale", "못도와줌", "도와주고 싶지만 제가 할 수 있는 일이 아니에요.", "vo/trainyard/female01/cit_pedestrian05.wav")
Schema.voices.Add("CitizenFemale", "대단", "용감한건지 무모한건지, 대단하네요.", "vo/trainyard/female01/cit_tvbust05.wav")
Schema.voices.Add("CitizenFemale", "상황별로", "별로 좋아보이지 않아요.", "vo/trainyard/female01/cit_window_use01.wav")
Schema.voices.Add("CitizenFemale", "오는중", "확실히 이곳으로 오고 있어요.", "vo/trainyard/female01/cit_window_use02.wav")
Schema.voices.Add("CitizenFemale", "터질일", "언젠간 터질 일이였어요.", "vo/trainyard/female01/cit_window_use03.wav")
Schema.voices.Add("CitizenFemale", "끝장", "이제 이 동네도 끝장이로군요.", "vo/trainyard/female01/cit_window_use04.wav")

Schema.voices.AddClass("Combine", function(client)
	return client:IsCombine()
end)

Schema.voices.AddClass("Dispatch", function(client)
	return client:IsDispatch()
end)

Schema.voices.AddClass("Breencast", function(client)
	return client:IsBreencast()
end)

Schema.voices.AddClass("CitizenMale", function(client)
	return !client:IsCombine() and !client:IsFemale()
end)

Schema.voices.AddClass("CitizenFemale", function(client)
	return !client:IsCombine() and client:IsFemale()
end)